/**
 * The browser half of the rule conformance suite.
 *
 * Every case here comes from `ruleConformance.fixture.json`, which is generated
 * by `tests/back/core/test_rules_conformance.py` from the Python interpreter's
 * own verdicts. So this file does not assert what someone believed the
 * semantics were; it asserts that the two runtimes agree, case by case. If the
 * two ever drift, this suite fails rather than the product misbehaving in front
 * of a user.
 *
 * Regenerate the fixture with:
 *   uv run pytest tests/back/core/test_rules_conformance.py
 */

import * as Yup from "yup";
import { validateYupSchema, yupToFormErrors } from "formik";

import fixture from "./ruleConformance.fixture.json";
import {
  PENDING,
  collectFieldNames,
  evaluate,
  evaluateRules,
  formatValue,
  withRules,
} from "./ruleEngine";

/** Decode an expected verdict from the fixture's JSON encoding. */
function decode(expected) {
  if (
    expected !== null &&
    typeof expected === "object" &&
    !Array.isArray(expected) &&
    expected.$pending === true
  ) {
    return PENDING;
  }
  return expected;
}

describe("rule interpreter conformance with the Python runtime", () => {
  it("reads a fixture generated by the backend", () => {
    expect(fixture.version).toBe(1);
    expect(fixture.named.length).toBeGreaterThan(30);
    expect(fixture.sweep.cases.length).toBeGreaterThan(1000);
  });

  it.each(fixture.named.map((c) => [c.name, c]))(
    "named case: %s",
    (_name, testCase) => {
      const actual = evaluate(testCase.ast, testCase.values, testCase.ctx);
      expect(actual).toEqual(decode(testCase.expect));
    },
  );

  it("agrees on every case of the seeded random sweep", () => {
    const { values, ctx, cases } = fixture.sweep;
    const divergences = [];
    cases.forEach((testCase, index) => {
      const actual = evaluate(
        testCase.ast,
        values,
        testCase.ctx_present ? ctx : null,
      );
      const expected = decode(testCase.expect);
      const agree =
        actual === expected ||
        (Array.isArray(actual) &&
          Array.isArray(expected) &&
          JSON.stringify(actual) === JSON.stringify(expected));
      if (!agree) {
        divergences.push({ index, ast: testCase.ast, actual, expected });
      }
    });
    // Report the first few rather than one opaque boolean: a divergence is a
    // conformance failure whose fix is to shrink the node set, and the reviewer
    // needs to see which node did it.
    expect(divergences.slice(0, 5)).toEqual([]);
    expect(divergences).toHaveLength(0);
  });

  it.each(fixture.formatting.map((c) => [JSON.stringify(c.value), c]))(
    "formats %s the same way as Python",
    (_label, testCase) => {
      expect(formatValue(testCase.value)).toBe(testCase.expect);
    },
  );

  it.each(fixture.rulesets.scenarios.map((s) => [s.name, s]))(
    "whole rule set: %s",
    (_name, scenario) => {
      const report = evaluateRules(
        fixture.rulesets.rules,
        scenario.values,
        scenario.ctx,
      );
      expect(report.errors).toEqual(scenario.expect.errors);
      expect([...report.pending].sort()).toEqual(scenario.expect.pending);
      const irrelevant = Object.entries(report.relevance)
        .filter(([, state]) => !state.relevant)
        .map(([name]) => name)
        .sort();
      expect(irrelevant).toEqual(scenario.expect.irrelevant);
    },
  );

  it("refuses to interpret a node it does not know instead of passing it", () => {
    expect(() =>
      evaluate({ n: "regex_match", a: { n: "lit", v: 1 } }, {}, null),
    ).toThrow(/Unknown rule node/);
  });
});

describe("live validation before submit", () => {
  // The rules the holdout splitter now declares, in the shape the backend
  // serves them after localize().
  const holdoutRules = [
    {
      kind: "check",
      id: "holdout.proportions_sum_to_one",
      targets: ["train", "validation", "test"],
      message:
        "Train, validation and test must sum to 1 (they add up to {total}).",
      expr: {
        n: "approx",
        a: {
          n: "sum",
          of: [
            { n: "field", f: "train" },
            { n: "field", f: "validation" },
            { n: "field", f: "test" },
          ],
        },
        b: { n: "lit", v: 1.0 },
        tol: 1e-6,
      },
      bindings: {
        total: {
          n: "sum",
          of: [
            { n: "field", f: "train" },
            { n: "field", f: "validation" },
            { n: "field", f: "test" },
          ],
        },
      },
      requires_ctx: false,
    },
    {
      kind: "check",
      id: "holdout.train_not_empty",
      targets: ["train"],
      message: "The train proportion must be greater than 0.",
      expr: {
        n: "cmp",
        op: "gt",
        a: { n: "field", f: "train" },
        b: { n: "lit", v: 0 },
      },
      bindings: {},
      requires_ctx: false,
    },
    {
      kind: "relevance",
      field: "random_state",
      when: { n: "is_true", of: { n: "field", f: "shuffle" } },
      effect: "disable",
      reason: "The random state has no effect while shuffling is disabled.",
    },
  ];

  const shape = {
    train: Yup.number().min(0).max(1).required(),
    validation: Yup.number().min(0).max(1).required(),
    test: Yup.number().min(0).max(1).required(),
    shuffle: Yup.boolean(),
    random_state: Yup.number().min(0).required(),
  };

  const schema = withRules(shape, holdoutRules);

  /** Validate the way formik does, and return its per-field error object. */
  async function errorsFor(values) {
    try {
      await validateYupSchema(values, schema);
      return {};
    } catch (error) {
      return yupToFormErrors(error);
    }
  }

  const complete = {
    train: 0.6,
    validation: 0.3,
    test: 0.1,
    shuffle: true,
    random_state: 42,
  };

  it("accepts 60/30/10, which an exact comparison rejects", async () => {
    // 0.6 + 0.3 + 0.1 === 0.9999999999999999 in IEEE-754, which is why the
    // pipeline editor's `!== 1` gate can never save this split.
    expect(0.6 + 0.3 + 0.1).not.toBe(1);
    await expect(errorsFor(complete)).resolves.toEqual({});
  });

  it("puts a cross-field message under every field the relation names", async () => {
    const errors = await errorsFor({ ...complete, test: 0.3 });
    expect(Object.keys(errors).sort()).toEqual(["test", "train", "validation"]);
    expect(errors.train).toBe(
      "Train, validation and test must sum to 1 (they add up to 1.2).",
    );
    expect(errors.test).toBe(errors.train);
  });

  it("interpolates the offending value into the message", async () => {
    const errors = await errorsFor({ ...complete, train: 0.5 });
    expect(errors.train).toContain("0.9");
  });

  it("stays silent while a referenced field is still empty", async () => {
    // Mid-edit is the normal state of a form. A relation that fires the moment
    // a field is cleared is worse than no relation, so a pending rule shows
    // nothing and only the field's own `required` remains.
    const errors = await errorsFor({ ...complete, train: undefined });
    expect(errors.validation).toBeUndefined();
    expect(errors.test).toBeUndefined();
    expect(errors.train).toBe("train is a required field");
  });

  it("lets a field's own constraint win over the relation on that field", async () => {
    const errors = await errorsFor({ ...complete, train: 1.4 });
    expect(errors.train).toBe("train must be less than or equal to 1");
    expect(errors.validation).toContain("must sum to 1");
  });

  it("reports the train-not-empty rule on its own field only", async () => {
    const errors = await errorsFor({
      ...complete,
      train: 0,
      validation: 0.5,
      test: 0.5,
    });
    expect(errors.train).toBe("The train proportion must be greater than 0.");
    expect(errors.validation).toBeUndefined();
  });

  it("drops an irrelevant field's own constraints, which an object test cannot", async () => {
    // Yup validates field schemas before object-level tests, so relevance has
    // to change the field's validator through `when`. This is the assertion
    // that proves it: with shuffling off, a negative seed is not an error.
    const withShuffle = await errorsFor({ ...complete, random_state: -1 });
    expect(withShuffle.random_state).toBeDefined();

    const withoutShuffle = await errorsFor({
      ...complete,
      shuffle: false,
      random_state: -1,
    });
    expect(withoutShuffle.random_state).toBeUndefined();
  });

  it("keeps a field relevant while its condition cannot be judged", async () => {
    // Never disable a control because something else has not been filled in.
    const report = evaluateRules(holdoutRules, {
      ...complete,
      shuffle: undefined,
    });
    expect(report.relevance.random_state.relevant).toBe(true);
  });

  it("reports relevance as render state, and never rewrites a value", async () => {
    // The alternative architecture that let the server echo values back as the
    // single store destroyed user input: set a seed, toggle shuffling off and
    // on, and the seed was gone. The engine here is read-only by construction,
    // so the value a user typed is the only copy and cannot be stomped.
    const values = { ...complete, random_state: 7 };
    const snapshot = JSON.stringify(values);

    const on = evaluateRules(holdoutRules, values);
    expect(on.relevance.random_state).toEqual({
      relevant: true,
      effect: "disable",
      reason: "The random state has no effect while shuffling is disabled.",
    });

    const off = evaluateRules(holdoutRules, { ...values, shuffle: false });
    expect(off.relevance.random_state.relevant).toBe(false);
    expect(off.relevance.random_state.effect).toBe("disable");

    // Neither call touched the caller's values, and nothing in the report is a
    // value the renderer is expected to write back.
    expect(JSON.stringify(values)).toBe(snapshot);
    expect(on).not.toHaveProperty("values");
    expect(off).not.toHaveProperty("values");
    expect(values.random_state).toBe(7);
  });

  it("carries no rules through when a schema declares none", async () => {
    const plain = withRules(shape, []);
    let thrown = null;
    try {
      await validateYupSchema({ ...complete, test: 0.3 }, plain);
    } catch (error) {
      thrown = error;
    }
    // Only the field constraints apply: 0.3 is a valid proportion on its own.
    expect(thrown).toBeNull();
  });
});

describe("helpers", () => {
  it("collects the field names an expression reads", () => {
    const ast = {
      n: "and",
      of: [
        {
          n: "cmp",
          op: "gt",
          a: { n: "field", f: "a" },
          b: { n: "lit", v: 0 },
        },
        { n: "is_true", of: { n: "field", f: "b" } },
        { n: "in", a: { n: "field", f: "a" }, b: { n: "ctx", k: "columns" } },
      ],
    };
    expect([...new Set(collectFieldNames(ast))].sort()).toEqual(["a", "b"]);
  });
});
