/**
 * The browser half of the rule interpreter.
 *
 * `DashAI/back/core/schema_fields/rules_eval.py` is the other half. Both walk
 * the same closed set of AST node shapes, and `ruleConformance.fixture.json`
 * (generated by pytest, asserted by both suites) is what keeps them honest. A
 * rule layer whose two runtimes quietly disagree is worse than no rule layer,
 * so treat that fixture as part of the mechanism rather than as test scaffolding.
 *
 * Read alongside the Python module: the node names, the operator set and the
 * three-valued semantics are deliberately identical, and every place the two
 * languages disagree about numbers or truthiness is closed here on purpose:
 *
 *  - PENDING is a third verdict. An expression that reads a field the user has
 *    not filled in, a field that is explicitly null, a context key that was not
 *    fetched, or an operand of the wrong type, is PENDING rather than false.
 *    Mid-edit is the normal state of a form; a rule that fires while someone is
 *    still typing is worse than no rule.
 *  - Booleans are not numbers, and only ever compare equal to booleans, because
 *    Python says `True == 1` and JavaScript says `true !== 1`.
 *  - `and` returns false as soon as one operand is false even when another is
 *    PENDING; `or` returns true as soon as one is true.
 *  - No `//`, no `%`, no string coercion: Python floors where JavaScript
 *    truncates, and that is exactly the kind of divergence this design exists
 *    to avoid.
 *
 * There is no `eval` and no expression parser anywhere in here, so a rule
 * arriving from a third-party plugin's schema cannot execute anything.
 */

import * as Yup from "yup";

/** The third verdict. A unique object so it can never be confused with a value. */
export const PENDING = Symbol("PENDING");

const MISSING = Symbol("MISSING");

const isNumber = (value) => typeof value === "number" && Number.isFinite(value);

/**
 * Render a value for interpolation into a rule message.
 *
 * Pinned digit for digit against `format_value` in rules_eval.py: floats are
 * rounded to six decimals and printed without a trailing `.0`, so a message
 * never reads `1.2000000000000002` in one runtime and `1.2` in the other.
 *
 * @param {*} value the value to render
 * @returns {string} its printable form
 */
export function formatValue(value) {
  if (value === PENDING || value === null || value === undefined) return "?";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") {
    if (!Number.isFinite(value)) return String(value);
    const rounded = Math.abs(value) < 1e21 ? Number(value.toFixed(6)) : value;
    return String(rounded);
  }
  if (typeof value === "string") return value;
  if (Array.isArray(value)) return value.map(formatValue).join(", ");
  return String(value);
}

/**
 * Equality that matches `_strict_equal` in rules_eval.py.
 *
 * @param {*} left first operand
 * @param {*} right second operand
 * @returns {boolean} whether the two are equal under the pinned semantics
 */
function strictEqual(left, right) {
  if (typeof left === "boolean" || typeof right === "boolean") {
    return (
      typeof left === "boolean" && typeof right === "boolean" && left === right
    );
  }
  if (isNumber(left) && isNumber(right)) return left === right;
  if (typeof left !== typeof right) return false;
  return left === right;
}

/**
 * Evaluate one expression AST node.
 *
 * @param {object} ast a node produced by `Expr.to_ast()` on the backend
 * @param {object} values the current field values
 * @param {object|null} ctx facts from outside the schema, or null if none were fetched
 * @returns {*} a value, or PENDING
 */
export function evaluate(ast, values, ctx) {
  const node = ast.n;

  switch (node) {
    case "lit":
      return ast.v;

    case "field": {
      const found = Object.prototype.hasOwnProperty.call(values, ast.f)
        ? values[ast.f]
        : MISSING;
      if (found === MISSING || found === null || found === undefined)
        return PENDING;
      // An empty text input reaching here as "" is not a number yet; the type
      // gates below turn that into PENDING rather than a spurious verdict.
      return found;
    }

    case "ctx": {
      if (ctx === null || ctx === undefined) return PENDING;
      const found = Object.prototype.hasOwnProperty.call(ctx, ast.k)
        ? ctx[ast.k]
        : MISSING;
      if (found === MISSING || found === null || found === undefined)
        return PENDING;
      return found;
    }

    case "add":
    case "sub":
    case "mul": {
      const left = evaluate(ast.a, values, ctx);
      const right = evaluate(ast.b, values, ctx);
      if (!isNumber(left) || !isNumber(right)) return PENDING;
      if (node === "add") return left + right;
      if (node === "sub") return left - right;
      return left * right;
    }

    case "sum": {
      let total = 0;
      for (const operand of ast.of) {
        const item = evaluate(operand, values, ctx);
        if (!isNumber(item)) return PENDING;
        total += item;
      }
      return total;
    }

    case "approx": {
      const left = evaluate(ast.a, values, ctx);
      const right = evaluate(ast.b, values, ctx);
      if (!isNumber(left) || !isNumber(right)) return PENDING;
      let difference = left - right;
      if (difference < 0) difference = -difference;
      return difference <= ast.tol;
    }

    case "cmp":
      return compare(ast, values, ctx);

    case "and": {
      const verdicts = ast.of.map((operand) => evaluate(operand, values, ctx));
      if (verdicts.some((verdict) => verdict === false)) return false;
      if (verdicts.some((verdict) => typeof verdict !== "boolean"))
        return PENDING;
      return true;
    }

    case "or": {
      const verdicts = ast.of.map((operand) => evaluate(operand, values, ctx));
      if (verdicts.some((verdict) => verdict === true)) return true;
      if (verdicts.some((verdict) => typeof verdict !== "boolean"))
        return PENDING;
      return false;
    }

    case "not": {
      const verdict = evaluate(ast.of, values, ctx);
      if (typeof verdict !== "boolean") return PENDING;
      return !verdict;
    }

    case "is_null": {
      const verdict = evaluate(ast.of, values, ctx);
      return verdict === PENDING || verdict === null || verdict === undefined;
    }

    case "is_true": {
      const verdict = evaluate(ast.of, values, ctx);
      if (verdict === PENDING) return PENDING;
      return verdict === true;
    }

    case "is_false": {
      const verdict = evaluate(ast.of, values, ctx);
      if (verdict === PENDING) return PENDING;
      return verdict === false;
    }

    case "in": {
      const needle = evaluate(ast.a, values, ctx);
      const haystack = evaluate(ast.b, values, ctx);
      if (needle === PENDING || !Array.isArray(haystack)) return PENDING;
      return haystack.some((item) => strictEqual(needle, item));
    }

    case "len": {
      const operand = evaluate(ast.of, values, ctx);
      if (!Array.isArray(operand) && typeof operand !== "string")
        return PENDING;
      return operand.length;
    }

    default:
      throw new Error(`Unknown rule node "${node}".`);
  }
}

function compare(ast, values, ctx) {
  const left = evaluate(ast.a, values, ctx);
  const right = evaluate(ast.b, values, ctx);
  if (left === PENDING || right === PENDING) return PENDING;

  if (ast.op === "eq" || ast.op === "ne") {
    const equal = strictEqual(left, right);
    return ast.op === "eq" ? equal : !equal;
  }

  const bothNumbers = isNumber(left) && isNumber(right);
  const bothStrings = typeof left === "string" && typeof right === "string";
  if (!bothNumbers && !bothStrings) return PENDING;
  if (ast.op === "lt") return left < right;
  if (ast.op === "lte") return left <= right;
  if (ast.op === "gt") return left > right;
  return left >= right;
}

/**
 * Fill a rule's `{binding}` placeholders.
 *
 * The message template crosses the wire already localized by the backend;
 * only the values are substituted here, by whichever runtime is reporting.
 *
 * @param {object} rule a serialized check
 * @param {object} values current field values
 * @param {object|null} ctx context payload or null
 * @returns {string} the message with its bindings substituted
 */
function interpolate(rule, values, ctx) {
  const message = rule.message;
  const bindings = rule.bindings || {};
  let text = typeof message === "string" ? message : String(message ?? "");
  for (const [name, expr] of Object.entries(bindings)) {
    text = text
      .split(`{${name}}`)
      .join(formatValue(evaluate(expr, values, ctx)));
  }
  return text;
}

/**
 * Evaluate a whole rule set.
 *
 * Relevance is resolved first, because a check touching an irrelevant field
 * must not run at all: with shuffling off, a rule about the random seed is not
 * satisfied, it is meaningless.
 *
 * @param {Array<object>} rules the `x-dashai-rules` payload
 * @param {object} values current field values
 * @param {object|null} ctx context payload, or null when none was fetched
 * @returns {{errors: object, pending: string[], relevance: object, violations: Array}}
 *   `errors` maps a field name to one message, ready to merge into formik's
 *   errors; `relevance` maps a field name to `{relevant, effect, reason}` for
 *   the renderer; `pending` lists the ids of checks that could not be judged.
 */
export function evaluateRules(rules, values, ctx = null) {
  const relevance = {};
  const errors = {};
  const pending = [];
  const violations = [];

  if (!Array.isArray(rules) || rules.length === 0) {
    return { errors, pending, relevance, violations };
  }

  for (const rule of rules) {
    if (rule.kind !== "relevance") continue;
    const verdict = evaluate(rule.when, values, ctx);
    // PENDING leaves the field relevant: never disable a control because
    // something else has not been filled in yet.
    const relevant = verdict !== false;
    relevance[rule.field] = {
      relevant,
      effect: rule.effect,
      ...(rule.reason !== undefined ? { reason: rule.reason } : {}),
    };
  }

  const irrelevant = new Set(
    Object.entries(relevance)
      .filter(([, state]) => !state.relevant)
      .map(([name]) => name),
  );

  for (const rule of rules) {
    if (rule.kind !== "check") continue;
    if (rule.targets.some((target) => irrelevant.has(target))) continue;
    if (rule.requires_ctx && (ctx === null || ctx === undefined)) {
      pending.push(rule.id);
      continue;
    }
    const verdict = evaluate(rule.expr, values, ctx);
    if (verdict === true) continue;
    if (verdict === false) {
      const message = interpolate(rule, values, ctx);
      violations.push({ ruleId: rule.id, targets: rule.targets, message });
      for (const target of rule.targets) {
        // A field constraint that already failed wins: it is closer to what the
        // user just typed than a relation over several fields.
        if (errors[target] === undefined) errors[target] = message;
      }
    } else {
      pending.push(rule.id);
    }
  }

  return { errors, pending, relevance, violations };
}

/**
 * Field names an expression reads.
 *
 * @param {object} ast an expression AST
 * @returns {string[]} every field name referenced inside it
 */
export function collectFieldNames(ast) {
  const found = [];
  const walk = (node) => {
    if (Array.isArray(node)) {
      node.forEach(walk);
      return;
    }
    if (node && typeof node === "object") {
      if (node.n === "field") found.push(node.f);
      Object.values(node).forEach(walk);
    }
  };
  walk(ast);
  return found;
}

/**
 * Make a Yup object schema enforce a rule set, so the errors appear as the user
 * types instead of after a submit and a round trip.
 *
 * Two mechanisms, because they do different jobs and one cannot do the other:
 *
 *  - Checks become a single object-level `test` that returns a `ValidationError`
 *    carrying one inner error per target field. Formik's `yupToFormErrors` maps
 *    those onto the fields, so a relation over three siblings shows its message
 *    under all three.
 *  - Relevance has to change the *field's own* validator, via `when`, because
 *    an object-level test cannot subtract an error the field schema already
 *    produced. Yup validates fields before object tests, and no schema field
 *    carries a default, so every field is required until something says
 *    otherwise.
 *
 * @param {object} shape the per-field validators, keyed by field name
 * @param {Array<object>} rules the `x-dashai-rules` payload
 * @param {() => (object|null)} getCtx returns the current context payload, or
 *   null. A getter rather than a value so the schema can be built once per
 *   component and still see a context that arrives later.
 * @returns {object} a Yup object schema
 */
export function withRules(shape, rules, getCtx = () => null) {
  if (!Array.isArray(rules) || rules.length === 0) {
    return Yup.object().shape(shape);
  }

  const relevanceRules = rules.filter((rule) => rule.kind === "relevance");
  const nextShape = { ...shape };

  for (const rule of relevanceRules) {
    const target = rule.field;
    const base = nextShape[target];
    if (base === undefined) continue;
    const deps = Array.from(new Set(collectFieldNames(rule.when))).filter(
      (name) => name !== target,
    );
    if (deps.length === 0) continue;
    // The `{is, then, otherwise}` form on purpose. Yup's bare-function builder
    // is called as `fn(...values, schema, options)` (see Condition.resolve in
    // yup 0.32), so reading the schema off the end of the argument list picks
    // up `options` instead and yup then throws "conditions must return a
    // schema object" — which formik turns into "no errors at all".
    nextShape[target] = base.when(deps, {
      is: (...depValues) => {
        const scope = {};
        deps.forEach((name, index) => {
          scope[name] = depValues[index];
        });
        // The condition asks "is this field irrelevant?". PENDING counts as
        // relevant: never drop a field's constraints because something else
        // has not been filled in yet.
        return evaluate(rule.when, scope, getCtx()) === false;
      },
      then: () => Yup.mixed().notRequired(),
      otherwise: (schema) => schema,
    });
  }

  return Yup.object()
    .shape(nextShape)
    .test("dashai-rules", null, function testRules(values) {
      let errors;
      try {
        errors = evaluateRules(rules, values || {}, getCtx()).errors;
      } catch (error) {
        // A bug in here must never read as "everything is valid". Formik maps
        // any non-ValidationError to an empty error object, so an unguarded
        // throw would silently switch off validation for the whole form. Fail
        // loudly on one field instead, and leave the real error in the console
        // for whoever has to fix it.
        // eslint-disable-next-line no-console
        console.error("dashai rule evaluation failed", error);
        return this.createError({
          path: rules.find((rule) => rule.kind === "check")?.targets?.[0],
          message: `Could not check this form's rules: ${error.message}`,
        });
      }
      const paths = Object.keys(errors);
      if (paths.length === 0) return true;
      return new Yup.ValidationError(
        paths.map((path) => this.createError({ path, message: errors[path] })),
      );
    });
}
