export const dataTypesList = [
  "null",
  "bool",
  //"int8",
  //"int16",
  "int32",
  "int64",
  //"uint8",
  //"uint16",
  "uint32",
  "uint64",
  //"float16",
  "float32",
  "float64",
  // Date/Time types disabled - no backend support
  // "time32[(s|ms)]",
  // "time64[(us|ns)]",
  // "timestamp[(s|ms|us|ns)]",
  // "timestamp[(s|ms|us|ns), tz=(tzstring)]",
  // "date32",
  // "date64",
  // "duration[(s|ms|us|ns)]",
  "decimal128",
  "decimal256",
  "binary",
  "large_binary",
  "string",
  "large_string",
];

export const columnTypesList = [
  "Integer",
  "Float",
  "Text",
  "Time",
  "Timestamp",
  "Duration",
  "Decimal",
  "Date",
  "Binary",
  "Categorical",
  "Image",
];

export const dataTypesbyColumnType = {
  Integer: ["int32", "int64", "uint32", "uint64"],
  Float: ["float32", "float64"],
  Text: ["string", "large_string"],
  Time: ["time32(s)", "time32(ms)", "time64(us)", "time64(ns)"],
  Boolean: ["bool"],
  Timestamp: [
    "timestamp(s)",
    "timestamp(ms)",
    "timestamp(us)",
    "timestamp(ns)",
    "timestamp(s), tz=(tzstring)",
    "timestamp(ms), tz=(tzstring)",
    "timestamp(us), tz=(tzstring)",
    "timestamp(ns), tz=(tzstring)",
  ],
  Duration: ["duration(s)", "duration(ms)", "duration(us)", "duration(ns)"],
  Decimal: ["decimal128", "decimal256"],
  Date: ["date32", "date64"],
  Binary: ["binary", "large_binary"],
  Categorical: ["string"],
  Image: ["string", "binary", "large_binary"],
};
