export const dataTypesList = [
  "null",
  "bool",
  "int8",
  "int16",
  "int32",
  "int64",
  "uint8",
  "uint16",
  "uint32",
  "uint64",
  "float16",
  "float32",
  "float64",
  "time32[(s|ms)]",
  "time64[(us|ns)]",
  "timestamp[(s|ms|us|ns)]",
  "timestamp[(s|ms|us|ns), tz=(tzstring)]",
  "date32",
  "date64",
  "duration[(s|ms|us|ns)]",
  "decimal128",
  "decimal256",
  "binary",
  "large_binary",
  "string",
  "large_string",
];

export const columnTypesList = ["Value", "ClassLabel"];
