from abc import ABCMeta, abstractmethod
from typing import Dict, Final, List

from DashAI.back.config_object import ConfigObject
from DashAI.back.models.RAG.documents.base_document import BaseDocument
from DashAI.back.models.RAG.documents.chunk import Chunk
from DashAI.back.models.RAG.exceptions import RAGWorkflowError


class BaseChunkingModel(ConfigObject, metaclass=ABCMeta):
    """
    Base class for chunking models.
    This class should be inherited by any specific chunking model implementation.
    """

    TYPE: Final[str] = "ChunkingModel"
    REQUIRED_EXTRA_KWARGS: Final[List[str]] = ["documents"]

    def __init__(self, **kwargs):
        """
        Initialize the chunking model with any necessary parameters.
        """
        self.documents: Dict[int, BaseDocument] = kwargs.pop("documents")
        self.parameters = self.validate_and_transform(kwargs)
        self.chunks = self.chunk_documents()
        self.id = None

    @abstractmethod
    def chunk_text(self, text: str, **kwargs) -> List[str]:
        """
        Chunk the input text into smaller pieces.

        Args:
            text (str): The input text to be chunked.
            **kwargs: Additional parameters for chunking.

        Returns:
            List[str]: A list of text chunks.
        """
        raise NotImplementedError("Subclasses must implement the chunk_text method.")

    def chunk_document(self, document: BaseDocument) -> Dict[int, Chunk]:
        """
        Chunk a single document using the chunk_text method.

        Args:
            document (BaseDocument): The input document to be chunked.
            **kwargs: Additional parameters for chunking, passed to `chunk_text`.

        Returns:
            Dict[int, Chunk]: A dictionary mapping chunk indices to Chunk objects.
        """
        if not isinstance(document, BaseDocument):
            raise TypeError("Input must be an instance of BaseDocument.")
        text = document.get_text()
        chunks_text = self.chunk_text(text)
        chunks = {}
        for idx, chunk_text in enumerate(chunks_text):
            chunk = Chunk(
                id=None,
                document_position=idx,
                document_id=document.id,
                text=chunk_text,
            )
            chunks[idx] = chunk
        return chunks

    def chunk_documents(self) -> Dict[int, Dict[int, Chunk]]:
        """
        Chunk documents using the chunk_document method.

        Returns:
            Dict[int, Dict[int, Chunk]]: A dictionary mapping document IDs to their respective
            dictionaries of chunk indices and Chunk objects.
        """
        chunked_documents = {}
        for document_id, document in self.documents.items():
            chunks = self.chunk_document(document)
            chunked_documents[document_id] = chunks
        return chunked_documents

    def get_chunks(self) -> Dict[int, Dict[int, Chunk]]:
        """
        Get the chunks generated by the chunking model.

        Returns:
            Dict[int, Dict[int, Chunk]]: A dictionary mapping document IDs to their respective
            dictionaries of chunk indices and Chunk objects.
        """
        return self.chunks

    def get_id(self) -> int:
        """
        Get the ID of the chunking model.

        Returns:
            int: The ID of the chunking model.
        """
        return self.id

    def set_id(self, id: int) -> None:
        """
        Set the ID of the chunking model.

        Args:
            id (int): The ID to set for the chunking model.
        """
        if self.id is None:
            self.id = id
        else:
            raise RAGWorkflowError(
                "Chunking model ID is already set and cannot be modified."
            )
