from abc import ABCMeta, abstractmethod
from typing import Dict, Final, List

from DashAI.back.config_object import ConfigObject
from DashAI.back.models.RAG.documents.base_document import BaseDocument
from DashAI.back.models.RAG.documents.chunk import Chunk
from DashAI.back.models.RAG.exceptions import RAGChunkingError


class BaseChunkingModel(ConfigObject, metaclass=ABCMeta):
    """Abstract base class for all chunking models.

    Defines the interface and common workflow for chunking strategies.
    Subclasses must implement :meth:`chunk_text`.
    """

    TYPE: Final[str] = "ChunkingModel"
    REQUIRED_EXTRA_KWARGS: Final[List[str]] = ["documents"]

    #: Unit ``chunk_size`` is expressed in: ``"characters"`` or ``"tokens"``.
    #: Lets callers convert a chunk size into a token budget without having to
    #: guess from the class name.
    CHUNK_UNIT: str = "characters"

    def __init__(self, **kwargs):
        """Initialize the chunking model.

        Validates that all required extra keyword arguments are present,
        stores the document mapping, and validates/transforms model parameters.

        Args:
            **kwargs: Must include a ``documents`` key mapping document IDs
                to :class:`BaseDocument` instances. Remaining keys are
                validated and transformed by :meth:`validate_and_transform`.

        Raises:
            RAGChunkingError: If a required extra keyword argument is missing.
        """
        for required_key in self.REQUIRED_EXTRA_KWARGS:
            if required_key not in kwargs:
                raise RAGChunkingError(
                    f"Missing required extra keyword argument: '{required_key}'"
                )
        self.documents: Dict[int, BaseDocument] = kwargs.pop("documents")
        self.parameters = self.validate_and_transform(kwargs)
        self.chunks = None
        self.id = None

    def compute_chunks(self) -> None:
        """Compute chunks if not already done."""
        if self.chunks is None:
            self.chunks = self.chunk_documents()

    @abstractmethod
    def chunk_text(self, text: str, **kwargs) -> List[str]:
        """
        Chunk the input text into smaller pieces.

        Args:
            text (str): The input text to be chunked.
            **kwargs: Additional parameters for chunking.

        Returns:
            List[str]: A list of text chunks.
        """
        raise NotImplementedError("Subclasses must implement the chunk_text method.")

    def chunk_document(self, document: BaseDocument) -> Dict[int, Chunk]:
        """
        Chunk a single document using the chunk_text method.

        Args:
            document (BaseDocument): The input document to be chunked.
            **kwargs: Additional parameters for chunking, passed to `chunk_text`.

        Returns:
            Dict[int, Chunk]: A dictionary mapping chunk indices to Chunk objects.
        """
        if not isinstance(document, BaseDocument):
            raise TypeError("Input must be an instance of BaseDocument.")
        text = document.get_text()
        chunks_text = self.chunk_text(text)
        chunks = {}
        for idx, chunk_text in enumerate(chunks_text):
            chunk = Chunk(
                id=None,
                document_position=idx,
                document_id=document.id,
                text=chunk_text,
            )
            chunks[idx] = chunk
        return chunks

    def chunk_documents(self) -> Dict[int, Dict[int, Chunk]]:
        """
        Chunk documents using the chunk_document method.

        Returns:
            Dict[int, Dict[int, Chunk]]: A dictionary mapping document IDs
            to their respective dictionaries of chunk indices and Chunk
            objects.
        """
        chunked_documents = {}
        for document_id, document in self.documents.items():
            chunks = self.chunk_document(document)
            chunked_documents[document_id] = chunks
        return chunked_documents

    def get_chunks(self) -> Dict[int, Dict[int, Chunk]]:
        """
        Get the chunks generated by the chunking model.

        Returns:
            Dict[int, Dict[int, Chunk]]: A dictionary mapping document IDs
            to their respective dictionaries of chunk indices and Chunk
            objects.
        """
        self.compute_chunks()
        return self.chunks

    def get_id(self) -> int:
        """
        Get the ID of the chunking model.

        Returns:
            int: The ID of the chunking model.
        """
        return self.id

    def set_id(self, id: int) -> None:
        """
        Set the ID of the chunking model.

        Args:
            id (int): The ID to set for the chunking model.
        """
        if self.id is None:
            self.id = id
        else:
            raise RAGChunkingError(
                "Chunking model ID is already set and cannot be modified."
            )
