repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
        exclude: "DashAI/front/tsconfig.json"
      - id: check-xml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.7
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.40.0"
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        args:
          - "--config=DashAI/front/eslint.config.js"
        additional_dependencies:
          - eslint
          - eslint-config-standard-with-typescript
          - eslint-plugin-import
          - eslint-plugin-n
          - eslint-plugin-promise
          - eslint-plugin-react
          - eslint-config-prettier
          - "@typescript-eslint/eslint-plugin"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.9-for-vscode" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        args:
          - "--config=DashAI/front/.prettierrc"
          - "--ignore-path=DashAI/front/.prettierignore"
exclude: "(migrations|generated)/.*"
