#!/usr/bin/env python

from subprocess import Popen
import webbrowser
url = "http://localhost:3000/"
procs = [Popen('python back/main.py', shell=True), Popen('python -m http.server 3000', shell=True, cwd='front/build')]
webbrowser.open(url, new=0, autoraise=True)
for p in procs:
   p.wait()
# subprocess.Popen('python back/main.py', shell=True)
# subprocess.Popen('python -m http.server 3000', shell=True, cwd='front')