[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 88
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "C4",  # flake8-comprehensions
    "I",   # isort
    "N",   # pep8-naming
    "YTT", # flake8-2020
    "B",   # flake8-bugbear
    "ISC", # flake8-implicit-str-concat
    "PIE", # flake8-pie
    "PT",  # flake8-pytest-style
    "Q",   # flake8-quotes
    "RSE", # flake8-raise
    "SIM", # flake8-simplify
    "TID", # flake8-tidy-imports
    "ERA", # eradicate
    "PD",  # pandas-vet
]
ignore = ["B008", "B010", "N806", "N817", "N999"]
exclude = [".git", "__pycache__", "__init__.py", ".mypy_cache", ".pytest_cache"]

[tool.ruff.pydocstyle]
convention = "numpy" # use numpy-style docstrings.


[tool.flake8]
max-line-length = 88
extend-ignore = "E203"
docstring_style = "numpy"
requirements-max-depth = 5
exclude = ".git,__pycache__,__init__.py,.mypy_cache,.pytest_cache"

[tool.pytest.ini_options]
minversion = "7.0"
testpaths = ["tests", "integration"]
addopts = ["--pdbcls=IPython.terminal.debugger:TerminalPdb"]

[tool.mypy]
plugins = ["pydantic.mypy", "sqlmypy"]
ignore_missing_imports = true
disallow_untyped_defs = true
