"""Unit that applies a single converter to the dataset in the context."""

import logging
from typing import TYPE_CHECKING, Any, Dict, List, Tuple

from DashAI.back.core.schema_fields import (
    BaseSchema,
    component_field,
    none_type,
    schema_field,
)
from DashAI.back.core.utils import MultilingualString
from DashAI.back.job.base_job import JobError
from DashAI.back.units.base_unit import BaseUnit
from DashAI.back.units.context import ExecutionContext

if TYPE_CHECKING:
    from DashAI.back.dataloaders.classes.dashai_dataset import DashAIDataset

log = logging.getLogger(__name__)

EMPTY_SCOPE: Dict[str, List] = {"columns": [], "rows": []}


def rebuild_dataset_with_transformed_columns(
    base: "DashAIDataset",
    transformed: "DashAIDataset",
    scope_column_names: List[str],
) -> "DashAIDataset":
    """
    Replaces specific columns in the base dataset with columns from the transformed
    dataset, preserving their original positions. Also appends any additional columns
    that were generated by the transformer at the end. Keeps the features and metadata
    consistent.

    Parameters
    ----------
    base : DashAIDataset
        The original dataset before transformation.

    transformed : DashAIDataset
        The dataset resulting from applying a transformer, containing updated and/or
        new columns.

    scope_column_names : List[str]
        Names of the columns that were originally selected for transformation.

    Returns
    -------
    DashAIDataset
        A new dataset with the specified columns replaced in place, new columns
        appended, and original metadata and split information preserved.
    """
    from DashAI.back.dataloaders.classes.dashai_dataset import modify_table

    original_columns = base.column_names
    transformed_cols = transformed.column_names

    transformed_cols_set = set(transformed_cols)
    scope_column_names_set = set(scope_column_names)

    removed_cols = [
        col for col in scope_column_names if col not in transformed_cols_set
    ]
    replacement_cols = [
        col for col in scope_column_names if col in transformed_cols_set
    ]
    new_cols = [col for col in transformed_cols if col not in scope_column_names_set]

    removed_cols_set = set(removed_cols)

    new_columns_order = []
    seen_cols = set()
    for col in original_columns:
        if col in removed_cols_set:
            continue
        if col not in seen_cols:
            new_columns_order.append(col)
            seen_cols.add(col)

    col_name_mapping = {}
    for col in new_cols:
        unique_col = col
        counter = 1
        while unique_col in seen_cols:
            unique_col = f"{col}_{counter}"
            counter += 1
        new_columns_order.append(unique_col)
        seen_cols.add(unique_col)
        col_name_mapping[col] = unique_col

    updated_arrays = {}
    for col in replacement_cols:
        if col in transformed_cols_set:
            updated_arrays[col] = transformed.arrow_table[col]
    for col, unique_col in col_name_mapping.items():
        if col in transformed_cols_set:
            updated_arrays[unique_col] = transformed.arrow_table[col]

    updated_types = base.types.copy()

    for col in removed_cols:
        if col in updated_types:
            del updated_types[col]

    for col in replacement_cols:
        if col in transformed.types:
            updated_types[col] = transformed.types[col]
    for col, unique_col in col_name_mapping.items():
        if col in transformed.types:
            updated_types[unique_col] = transformed.types[col]

    modified_dataset = modify_table(base, updated_arrays, types=updated_types)
    modified_dataset = modified_dataset.select_columns(new_columns_order)

    return modified_dataset


class ApplyConverterSchema(BaseSchema):
    converter: schema_field(
        component_field(parent="BaseConverter"),
        placeholder={"component": "ColumnRemover", "params": {}},
        description=MultilingualString(
            en="Converter to apply, together with its own configuration.",
            es="Convertidor a aplicar, junto con su propia configuración.",
            pt="Conversor a aplicar, junto com a sua própria configuração.",
            de="Anzuwendender Konverter samt seiner eigenen Konfiguration.",
            zh="要应用的转换器及其自身的配置。",
        ),
        alias=MultilingualString(
            en="Converter",
            es="Convertidor",
            pt="Conversor",
            de="Konverter",
            zh="转换器",
        ),
    )  # type: ignore
    scope: schema_field(
        none_type(dict),
        placeholder={"columns": [], "rows": []},
        description=MultilingualString(
            en="Part of the dataset the converter applies to: 'columns' is a "
            "list of {'idx': n} and 'rows' a list of n, both 1-based. An "
            "empty column list means every column.",
            es="Parte del conjunto de datos a la que se aplica el convertidor: "
            "'columns' es una lista de {'idx': n} y 'rows' una lista de n, "
            "ambas con base 1. Una lista de columnas vacía significa todas "
            "las columnas.",
            pt="Parte do conjunto de dados à qual o conversor se aplica: "
            "'columns' é uma lista de {'idx': n} e 'rows' uma lista de n, "
            "ambas com base 1. Uma lista de colunas vazia significa todas "
            "as colunas.",
            de="Teil des Datensatzes, auf den der Konverter angewendet wird: "
            "'columns' ist eine Liste von {'idx': n} und 'rows' eine Liste "
            "von n, beide 1-basiert. Eine leere Spaltenliste bedeutet alle "
            "Spalten.",
            zh="转换器作用的数据集范围：'columns' 是 {'idx': n} 的列表，"
            "'rows' 是 n 的列表，均从 1 开始。空的列列表表示所有列。",
        ),
        alias=MultilingualString(
            en="Scope",
            es="Alcance",
            pt="Escopo",
            de="Geltungsbereich",
            zh="范围",
        ),
    )  # type: ignore
    target: schema_field(
        none_type(dict),
        placeholder=None,
        description=MultilingualString(
            en="Target column handed to the converter as y, as {'idx': n} with "
            "n 1-based. Leave empty for unsupervised converters.",
            es="Columna objetivo entregada al convertidor como y, como "
            "{'idx': n} con n en base 1. Dejar vacío para convertidores no "
            "supervisados.",
            pt="Coluna alvo entregue ao conversor como y, como {'idx': n} com "
            "n com base 1. Deixe vazio para conversores não supervisionados.",
            de="Zielspalte, die dem Konverter als y übergeben wird, als "
            "{'idx': n} mit 1-basiertem n. Für unüberwachte Konverter leer "
            "lassen.",
            zh="作为 y 传给转换器的目标列，格式为 {'idx': n}，n 从 1 开始。"
            "无监督转换器留空。",
        ),
        alias=MultilingualString(
            en="Target column",
            es="Columna objetivo",
            pt="Coluna alvo",
            de="Zielspalte",
            zh="目标列",
        ),
    )  # type: ignore


class ApplyConverterUnit(BaseUnit):
    """Fit one converter on the scoped data and transform the dataset with it.

    Reads ``dataset`` and writes ``dataset``: the same key on both sides, so any
    number of these can be chained in one context, each one seeing what the
    previous one produced.

    That is also why nothing about column identity ever crosses the context
    boundary. The scope is expressed as 1-based column and row indexes, and
    those indexes are resolved against ``dataset.column_names`` read at the top
    of ``execute`` — the dataset as it is *right now*. A converter that renames,
    drops or adds columns changes what index 3 means, so a resolved column list
    published to the context would be stale for the very next converter.
    """

    SCHEMA = ApplyConverterSchema

    REQUIRES = ("dataset",)
    PROVIDES = ("dataset",)

    def __init__(self, **config) -> None:
        super().__init__(**config)
        # Memoized on the instance, never in the context: two units of this
        # class can live in the same context and they are different converters.
        self._converter_class = None

    @property
    def _converter_name(self) -> str:
        return self.config["converter"]["component"]

    def _scope(self) -> Dict[str, List]:
        """The configured scope, tolerating an explicit ``None``.

        The API schema always writes the ``scope`` key but allows it to be null,
        so a converter saved without a scope arrives here as ``None`` rather
        than as a missing key.
        """
        return self.config.get("scope") or EMPTY_SCOPE

    def _target_index(self) -> int:
        """The 1-based target column index, or None when there is no target."""
        target = self.config.get("target")
        if target is None:
            return None
        return target.get("idx")

    def _check_target_bounds(self, dataset: "DashAIDataset") -> None:
        """Reject a target index that does not point at a column.

        Checked against the dataset in hand rather than once up front: when
        several converters are chained the column count changes underneath, and
        an unchecked index would surface as a bare IndexError.
        """
        target_column_index = self._target_index()
        if target_column_index is None:
            return

        if int(target_column_index) < 1 or int(target_column_index) > len(
            dataset.features
        ):
            raise JobError(
                f"Target column index {target_column_index} is out of bounds"
            )

    def _resolve_converter(self):
        """Look the converter class up in the registry, once per instance."""
        if self._converter_class is not None:
            return self._converter_class

        from kink import di

        component_registry = di["component_registry"]
        converter_name = self._converter_name

        try:
            self._converter_class = component_registry[converter_name]["class"]
        except KeyError as e:
            log.exception(e)
            raise JobError(f"Error importing converter {converter_name}: {e}") from e

        return self._converter_class

    def _resolve_scope(
        self, dataset: "DashAIDataset"
    ) -> Tuple[List[str], List[int], Any]:
        """Turn the 1-based scope into names and indexes for this dataset."""
        scope = self._scope()
        column_names = dataset.column_names

        columns_scope = [column["idx"] - 1 for column in scope["columns"]]
        scope_column_indexes = sorted(set(columns_scope))

        if not scope_column_indexes:
            scope_column_indexes = list(range(len(dataset.features)))

        scope_column_names = [column_names[index] for index in scope_column_indexes]

        rows_scope = [row - 1 for row in scope["rows"]]
        scope_rows_indexes = sorted(set(rows_scope))

        target_column_name = None
        target_column_index = self._target_index()
        if target_column_index is not None:
            target_column_name = column_names[int(target_column_index) - 1]

        return scope_column_names, scope_rows_indexes, target_column_name

    def validate(self, ctx: ExecutionContext) -> None:
        """Reject an out-of-bounds target before any work is done."""
        self._check_target_bounds(ctx.require("dataset"))

    def execute(self, ctx: ExecutionContext) -> None:
        loaded_dataset: "DashAIDataset" = ctx.require("dataset")
        converter_name = self._converter_name

        converter_constructor = self._resolve_converter()
        converter_instance = converter_constructor(
            **(self.config["converter"].get("params") or {})
        )

        self._check_target_bounds(loaded_dataset)
        (
            scope_column_names,
            scope_rows_indexes,
            target_column_name,
        ) = self._resolve_scope(loaded_dataset)

        log.info(f"Applying converter: {converter_name}")

        y_dataset_fit = None
        y_full_transform = None
        if target_column_name is not None:
            y_dataset_fit = loaded_dataset.select_columns([target_column_name])
            if scope_rows_indexes:
                y_dataset_fit = y_dataset_fit.select(scope_rows_indexes)
                y_full_transform = loaded_dataset.select_columns([target_column_name])
            else:
                y_full_transform = y_dataset_fit

        X_dataset_fit = loaded_dataset.select_columns(scope_column_names)

        if scope_rows_indexes:
            X_dataset_fit = X_dataset_fit.select(scope_rows_indexes)

        try:
            converter_instance = converter_instance.fit(X_dataset_fit, y_dataset_fit)
        except ValueError as e:
            log.error(f"Validation error in {converter_name}: {e}")
            raise JobError(f"Validation error fitting {converter_name}: {e}") from e
        except Exception as e:
            log.exception(e)
            raise JobError(f"Error fitting converter {converter_name}: {e}") from e

        if scope_rows_indexes:
            X_full_transform = loaded_dataset.select_columns(scope_column_names)
        else:
            # Deliberately the *same object* as the one passed to fit, not an
            # equal one: converters such as TypeCast key a cache off the
            # identity of the dataset they were fitted on and skip recomputing
            # when transform receives it again.
            X_full_transform = X_dataset_fit

        try:
            transformed_dataset = converter_instance.transform(
                X_full_transform, y_full_transform
            )
        except Exception as e:
            log.exception(e)
            raise JobError(f"Error transforming data with {converter_name}: {e}") from e

        if type(converter_instance).CHANGES_ROW_COUNT:
            loaded_dataset = transformed_dataset
        else:
            loaded_dataset = rebuild_dataset_with_transformed_columns(
                loaded_dataset,
                transformed_dataset,
                scope_column_names,
            )

        ctx.put("dataset", loaded_dataset)
