"""Shared scope resolution and slicing for the converter units.

The three converter units — fit, transform, and the fused apply — all express
which part of a dataset they touch the same way, and all resolve it the same
way. That logic lives here so the fused path and the split path cannot drift
apart.
"""

import logging
from typing import TYPE_CHECKING, Dict, List, Optional, Tuple

from DashAI.back.core.schema_fields import (
    component_field,
    none_type,
    schema_field,
)
from DashAI.back.core.utils import MultilingualString
from DashAI.back.job.base_job import JobError

if TYPE_CHECKING:
    from DashAI.back.dataloaders.classes.dashai_dataset import DashAIDataset

log = logging.getLogger(__name__)

EMPTY_SCOPE: Dict[str, List] = {"columns": [], "rows": []}


def converter_field():
    """Schema field for picking a converter and configuring it."""
    return schema_field(
        component_field(parent="BaseConverter"),
        placeholder={"component": "ColumnRemover", "params": {}},
        description=MultilingualString(
            en="Converter to apply, together with its own configuration.",
            es="Convertidor a aplicar, junto con su propia configuración.",
            pt="Conversor a aplicar, junto com a sua própria configuração.",
            de="Anzuwendender Konverter samt seiner eigenen Konfiguration.",
            zh="要应用的转换器及其自身的配置。",
        ),
        alias=MultilingualString(
            en="Converter",
            es="Convertidor",
            pt="Conversor",
            de="Konverter",
            zh="转换器",
        ),
    )


def scope_field():
    """Schema field for the part of the dataset a converter touches."""
    return schema_field(
        none_type(dict),
        placeholder={"columns": [], "rows": []},
        description=MultilingualString(
            en="Part of the dataset the converter applies to: 'columns' is a "
            "list of {'idx': n} and 'rows' a list of n, both 1-based. An "
            "empty column list means every column.",
            es="Parte del conjunto de datos a la que se aplica el convertidor: "
            "'columns' es una lista de {'idx': n} y 'rows' una lista de n, "
            "ambas con base 1. Una lista de columnas vacía significa todas "
            "las columnas.",
            pt="Parte do conjunto de dados à qual o conversor se aplica: "
            "'columns' é uma lista de {'idx': n} e 'rows' uma lista de n, "
            "ambas com base 1. Uma lista de colunas vazia significa todas "
            "as colunas.",
            de="Teil des Datensatzes, auf den der Konverter angewendet wird: "
            "'columns' ist eine Liste von {'idx': n} und 'rows' eine Liste "
            "von n, beide 1-basiert. Eine leere Spaltenliste bedeutet alle "
            "Spalten.",
            zh="转换器作用的数据集范围：'columns' 是 {'idx': n} 的列表，"
            "'rows' 是 n 的列表，均从 1 开始。空的列列表表示所有列。",
        ),
        alias=MultilingualString(
            en="Scope",
            es="Alcance",
            pt="Escopo",
            de="Geltungsbereich",
            zh="范围",
        ),
    )


def target_field():
    """Schema field for the column handed to the converter as ``y``."""
    return schema_field(
        none_type(dict),
        placeholder=None,
        description=MultilingualString(
            en="Target column handed to the converter as y, as {'idx': n} with "
            "n 1-based. Leave empty for unsupervised converters.",
            es="Columna objetivo entregada al convertidor como y, como "
            "{'idx': n} con n en base 1. Dejar vacío para convertidores no "
            "supervisados.",
            pt="Coluna alvo entregue ao conversor como y, como {'idx': n} com "
            "n com base 1. Deixe vazio para conversores não supervisionados.",
            de="Zielspalte, die dem Konverter als y übergeben wird, als "
            "{'idx': n} mit 1-basiertem n. Für unüberwachte Konverter leer "
            "lassen.",
            zh="作为 y 传给转换器的目标列，格式为 {'idx': n}，n 从 1 开始。"
            "无监督转换器留空。",
        ),
        alias=MultilingualString(
            en="Target column",
            es="Columna objetivo",
            pt="Coluna alvo",
            de="Zielspalte",
            zh="目标列",
        ),
    )


def rebuild_dataset_with_transformed_columns(
    base: "DashAIDataset",
    transformed: "DashAIDataset",
    scope_column_names: List[str],
) -> "DashAIDataset":
    """
    Replaces specific columns in the base dataset with columns from the transformed
    dataset, preserving their original positions. Also appends any additional columns
    that were generated by the transformer at the end. Keeps the features and metadata
    consistent.

    Parameters
    ----------
    base : DashAIDataset
        The original dataset before transformation.

    transformed : DashAIDataset
        The dataset resulting from applying a transformer, containing updated and/or
        new columns.

    scope_column_names : List[str]
        Names of the columns that were originally selected for transformation.

    Returns
    -------
    DashAIDataset
        A new dataset with the specified columns replaced in place, new columns
        appended, and original metadata and split information preserved.
    """
    from DashAI.back.dataloaders.classes.dashai_dataset import modify_table

    original_columns = base.column_names
    transformed_cols = transformed.column_names

    transformed_cols_set = set(transformed_cols)
    scope_column_names_set = set(scope_column_names)

    removed_cols = [
        col for col in scope_column_names if col not in transformed_cols_set
    ]
    replacement_cols = [
        col for col in scope_column_names if col in transformed_cols_set
    ]
    new_cols = [col for col in transformed_cols if col not in scope_column_names_set]

    removed_cols_set = set(removed_cols)

    new_columns_order = []
    seen_cols = set()
    for col in original_columns:
        if col in removed_cols_set:
            continue
        if col not in seen_cols:
            new_columns_order.append(col)
            seen_cols.add(col)

    col_name_mapping = {}
    for col in new_cols:
        unique_col = col
        counter = 1
        while unique_col in seen_cols:
            unique_col = f"{col}_{counter}"
            counter += 1
        new_columns_order.append(unique_col)
        seen_cols.add(unique_col)
        col_name_mapping[col] = unique_col

    updated_arrays = {}
    for col in replacement_cols:
        if col in transformed_cols_set:
            updated_arrays[col] = transformed.arrow_table[col]
    for col, unique_col in col_name_mapping.items():
        if col in transformed_cols_set:
            updated_arrays[unique_col] = transformed.arrow_table[col]

    updated_types = base.types.copy()

    for col in removed_cols:
        if col in updated_types:
            del updated_types[col]

    for col in replacement_cols:
        if col in transformed.types:
            updated_types[col] = transformed.types[col]
    for col, unique_col in col_name_mapping.items():
        if col in transformed.types:
            updated_types[unique_col] = transformed.types[col]

    modified_dataset = modify_table(base, updated_arrays, types=updated_types)
    modified_dataset = modified_dataset.select_columns(new_columns_order)

    return modified_dataset


class ConverterScopeMixin:
    """Scope handling shared by the converter units.

    Deliberately **not** named ``Base*`` and deliberately not inheriting from
    ``BaseUnit``. ``ComponentRegistry._get_base_type`` walks the MRO for
    ancestors whose name contains "Base" and that declare a ``TYPE``, and
    rejects a component with more than one candidate — an intermediate class
    called ``BaseConverterUnit`` would be a second candidate and break the
    registration of every unit inheriting from it.
    """

    def _scope(self) -> Dict[str, List]:
        """The configured scope, tolerating an explicit ``None``.

        The API schema always writes the ``scope`` key but allows it to be null,
        so a converter saved without a scope arrives here as ``None`` rather
        than as a missing key.
        """
        return self.config.get("scope") or EMPTY_SCOPE

    def _target_index(self) -> Optional[int]:
        """The 1-based target column index, or None when there is no target."""
        target = self.config.get("target")
        if target is None:
            return None
        return target.get("idx")

    def _check_target_bounds(self, dataset: "DashAIDataset") -> None:
        """Reject a target index that does not point at a column.

        Checked against the dataset in hand rather than once up front: when
        several converters are chained the column count changes underneath, and
        an unchecked index would surface as a bare IndexError.
        """
        target_column_index = self._target_index()
        if target_column_index is None:
            return

        if int(target_column_index) < 1 or int(target_column_index) > len(
            dataset.features
        ):
            raise JobError(
                f"Target column index {target_column_index} is out of bounds"
            )

    def _resolve_scope(
        self, dataset: "DashAIDataset"
    ) -> Tuple[List[str], List[int], Optional[str]]:
        """Turn the 1-based scope into names and indexes for **this** dataset.

        Always resolved against the dataset in hand, never against a list
        carried through the context: a converter that renames, drops or adds
        columns changes what index 3 means for whatever runs next.
        """
        scope = self._scope()
        column_names = dataset.column_names

        columns_scope = [column["idx"] - 1 for column in scope["columns"]]
        scope_column_indexes = sorted(set(columns_scope))

        if not scope_column_indexes:
            scope_column_indexes = list(range(len(dataset.features)))

        scope_column_names = [column_names[index] for index in scope_column_indexes]

        rows_scope = [row - 1 for row in scope["rows"]]
        scope_rows_indexes = sorted(set(rows_scope))

        target_column_name = None
        target_column_index = self._target_index()
        if target_column_index is not None:
            target_column_name = column_names[int(target_column_index) - 1]

        return scope_column_names, scope_rows_indexes, target_column_name

    def _slice_for_fit(
        self,
        dataset: "DashAIDataset",
        scope_column_names: List[str],
        scope_rows_indexes: List[int],
        target_column_name: Optional[str],
    ) -> Tuple["DashAIDataset", Optional["DashAIDataset"]]:
        """The X and y a converter is fitted on: scoped columns, scoped rows."""
        y_dataset = None
        if target_column_name is not None:
            y_dataset = dataset.select_columns([target_column_name])
            if scope_rows_indexes:
                y_dataset = y_dataset.select(scope_rows_indexes)

        x_dataset = dataset.select_columns(scope_column_names)
        if scope_rows_indexes:
            x_dataset = x_dataset.select(scope_rows_indexes)

        return x_dataset, y_dataset

    def _slice_for_transform(
        self,
        dataset: "DashAIDataset",
        scope_column_names: List[str],
        target_column_name: Optional[str],
    ) -> Tuple["DashAIDataset", Optional["DashAIDataset"]]:
        """The X and y a converter transforms: scoped columns, **every** row.

        A row scope narrows what the converter learns from, never what it is
        applied to.
        """
        y_dataset = None
        if target_column_name is not None:
            y_dataset = dataset.select_columns([target_column_name])

        return dataset.select_columns(scope_column_names), y_dataset

    def _merge_transformed(
        self,
        converter_instance,
        dataset: "DashAIDataset",
        transformed_dataset: "DashAIDataset",
        scope_column_names: List[str],
    ) -> "DashAIDataset":
        """Fold the transform output back into the dataset.

        A converter that changes the row count cannot have its columns merged
        back position by position, so its output replaces the dataset outright.
        """
        if type(converter_instance).CHANGES_ROW_COUNT:
            return transformed_dataset

        return rebuild_dataset_with_transformed_columns(
            dataset,
            transformed_dataset,
            scope_column_names,
        )

    def _fit(self, converter_instance, x_dataset, y_dataset, converter_name):
        """Fit a converter, preserving the job's two error messages."""
        try:
            return converter_instance.fit(x_dataset, y_dataset)
        except ValueError as e:
            log.error(f"Validation error in {converter_name}: {e}")
            raise JobError(f"Validation error fitting {converter_name}: {e}") from e
        except Exception as e:
            log.exception(e)
            raise JobError(f"Error fitting converter {converter_name}: {e}") from e

    def _transform(self, converter_instance, x_dataset, y_dataset, converter_name):
        """Transform with a fitted converter, preserving the job's message."""
        try:
            return converter_instance.transform(x_dataset, y_dataset)
        except Exception as e:
            log.exception(e)
            raise JobError(f"Error transforming data with {converter_name}: {e}") from e
