"""Delete task_name and adds dataloader name to Dataset model

Revision ID: 649c500185b8
Revises: 80faf11605a2
Create Date: 2023-08-09 08:43:29.112965

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "649c500185b8"
down_revision = "80faf11605a2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dataset", sa.Column("feature_names", sa.JSON(), nullable=False))
    op.add_column("dataset", sa.Column("dataset_name", sa.String(), nullable=False))
    op.drop_column("dataset", "task_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dataset", sa.Column("task_name", sa.VARCHAR(), nullable=False))
    op.drop_column("dataset", "dataset_name")
    op.drop_column("dataset", "feature_names")
    # ### end Alembic commands ###
