from DashAI.back.models.hugging_face.deep_seek_model import DeepSeekModel
from DashAI.back.models.hugging_face.qwen_model import Qwen25_05BInstruct, Qwen25_15BInstruct
from DashAI.back.models.hugging_face.phi_4_mini_instruct_model import Phi4MiniInstructModel
