import pyarrow as pa
import pytest

from DashAI.back.types.value_types import (
    Binary,
    Decimal,
    Duration,
    Float,
    Integer,
    Text,
)


@pytest.mark.parametrize(
    ("da_type", "bad_arrow_t"),
    [
        (Integer, pa.float16()),
        (Integer, pa.float32()),
        (Integer, pa.float64()),
        (Integer, pa.string()),
        (Integer, pa.large_string()),
        (Integer, pa.duration("s")),
        (Integer, pa.decimal128(10, 2)),
        (Integer, pa.binary()),
        (Integer, pa.large_binary()),
        (Float, pa.int8()),
        (Float, pa.int16()),
        (Float, pa.int32()),
        (Float, pa.int64()),
        (Float, pa.uint8()),
        (Float, pa.uint16()),
        (Float, pa.uint32()),
        (Float, pa.uint64()),
        (Float, pa.string()),
        (Float, pa.large_string()),
        (Float, pa.duration("s")),
        (Float, pa.decimal128(10, 2)),
        (Float, pa.binary()),
        (Float, pa.large_binary()),
        (Text, pa.int8()),
        (Text, pa.int16()),
        (Text, pa.int32()),
        (Text, pa.int64()),
        (Text, pa.uint8()),
        (Text, pa.uint16()),
        (Text, pa.uint32()),
        (Text, pa.uint64()),
        (Text, pa.duration("s")),
        (Text, pa.decimal128(10, 2)),
        (Text, pa.binary()),
        (Text, pa.large_binary()),
        # Date, Time, Timestamp checks should be implemented when their pa.types are
        # implemented
        # Instead of using a string type (Unless it's decided to use string types
        # + format for them)
        (Duration, pa.int8()),
        (Duration, pa.int16()),
        (Duration, pa.int32()),
        (Duration, pa.int64()),
        (Duration, pa.uint8()),
        (Duration, pa.uint16()),
        (Duration, pa.uint32()),
        (Duration, pa.uint64()),
        (Duration, pa.string()),
        (Duration, pa.large_string()),
        (Duration, pa.decimal128(10, 2)),
        (Duration, pa.binary()),
        (Duration, pa.large_binary()),
        (Decimal, pa.int8()),
        (Decimal, pa.int16()),
        (Decimal, pa.int32()),
        (Decimal, pa.int64()),
        (Decimal, pa.uint8()),
        (Decimal, pa.uint16()),
        (Decimal, pa.uint32()),
        (Decimal, pa.uint64()),
        (Decimal, pa.string()),
        (Decimal, pa.large_string()),
        (Decimal, pa.duration("s")),
        (Decimal, pa.binary()),
        (Decimal, pa.large_binary()),
        (Binary, pa.int8()),
        (Binary, pa.int16()),
        (Binary, pa.int32()),
        (Binary, pa.int64()),
        (Binary, pa.uint8()),
        (Binary, pa.uint16()),
        (Binary, pa.uint32()),
        (Binary, pa.uint64()),
        (Binary, pa.string()),
        (Binary, pa.large_string()),
        (Binary, pa.duration("s")),
        (Binary, pa.decimal128(10, 2)),
    ],
    ids=[
        "Integer-float16",
        "Integer-float32",
        "Integer-float64",
        "Integer-string",
        "Integer-large_string",
        "Integer-duration",
        "Integer-decimal",
        "Integer-binary",
        "Integer-large_binary",
        "Float-int8",
        "Float-int16",
        "Float-int32",
        "Float-int64",
        "Float-uint8",
        "Float-uint16",
        "Float-uint32",
        "Float-uint64",
        "Float-string",
        "Float-large_string",
        "Float-duration",
        "Float-decimal",
        "Float-binary",
        "Float-large_binary",
        "Text-int8",
        "Text-int16",
        "Text-int32",
        "Text-int64",
        "Text-uint8",
        "Text-uint16",
        "Text-uint32",
        "Text-uint64",
        "Text-duration",
        "Text-decimal",
        "Text-binary",
        "Text-large_binary",
        "Duration-int8",
        "Duration-int16",
        "Duration-int32",
        "Duration-int64",
        "Duration-uint8",
        "Duration-uint16",
        "Duration-uint32",
        "Duration-uint64",
        "Duration-string",
        "Duration-large_string",
        "Duration-decimal",
        "Duration-binary",
        "Duration-large_binary",
        "Decimal-int8",
        "Decimal-int16",
        "Decimal-int32",
        "Decimal-int64",
        "Decimal-uint8",
        "Decimal-uint16",
        "Decimal-uint32",
        "Decimal-uint64",
        "Decimal-string",
        "Decimal-large_string",
        "Decimal-duration",
        "Decimal-binary",
        "Decimal-large_binary",
        "Binary-int8",
        "Binary-int16",
        "Binary-int32",
        "Binary-int64",
        "Binary-uint8",
        "Binary-uint16",
        "Binary-uint32",
        "Binary-uint64",
        "Binary-string",
        "Binary-large_string",
        "Binary-duration",
        "Binary-decimal",
    ],
)
def test_dashai_types_init_invalid(da_type, bad_arrow_t):
    with pytest.raises(ValueError):  # noqa: PT011
        da_type(bad_arrow_t)
