import React, { useEffect } from "react";
import { createPipeline } from "../../../api/pipeline";

export function RunOrder(node, edges, nodes, nodeData) {
  let orderedNodes = [];
  let currentNode = node;

  while (true) {
    const incomingEdge = edges.find((edge) => edge.target === currentNode.id);
    if (!incomingEdge) break;
    const sourceNode = nodes.find((n) => n.id === incomingEdge.source);
    if (!sourceNode) break;

    orderedNodes.unshift({
      id: sourceNode.id,
      type: sourceNode.type,
      label: sourceNode.data.label,
      config: nodeData[sourceNode.id] || {},
    });

    currentNode = sourceNode;
  }

  return orderedNodes;
}

export function RunNode({ node, edges, nodes, pipelineName = "pipeline", onSaved, nodeData }) {
  useEffect(() => {
    const order = RunOrder(node, edges, nodes, nodeData);

    const savePipeline = async () => {
      try {
        const formData = {
          name: pipelineName,
          description: "A pipeline generated by React",
          steps: order,
        };
        console.log(formData);

        const response = await createPipeline(formData);
        console.log("Pipeline saved successfully:", response);
        alert("Pipeline saved successfully!");
      } catch (error) {
        console.error("Error saving pipeline:", error);
        alert("Failed to save pipeline. Check the console for details.");
      }
    };

    savePipeline();

    setTimeout(() => {
      onSaved();
    }, 2000);
  }, [node, edges, nodes, pipelineName, onSaved, nodeData]);

  return null;
}

export function Run(nodes, nodeData){
  const steps = nodes.map((node) => ({
    id: node.id,
    type: node.type,
    label: node.data.label,
    config: nodeData[node.id] || {},
  }));

  const savePipeline = async () => {
    try {
      const formData = {
        steps: steps,
        exploration: null,
        train: null,
        prediction: null,
      };
      console.log(formData);

      const response = await createPipeline(formData);
      console.log("Pipeline saved successfully:", response);
      alert("Pipeline saved successfully!");
    } catch (error) {
      console.error("Error saving pipeline:", error);
      alert("Failed to save pipeline. Check the console for details.");
    }
  };

  savePipeline();
} 