"""add StatisticalTest table

Revision ID: 0615701e8d16
Revises: 896c39f514fe
Create Date: 2026-06-06 23:26:17.839229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0615701e8d16'
down_revision: Union[str, None] = '896c39f514fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistical_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('model_session_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('test_name', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_split', sa.String(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('run_ids', sa.JSON(), nullable=False),
    sa.Column('run_names', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('statistic', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('significant', sa.Boolean(), nullable=False),
    sa.Column('interpretation', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('posthoc', sa.JSON(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_session_id'], ['model_session.id'], name=op.f('fk_statistical_test_model_session_id_model_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statistical_test'))
    )
    with op.batch_alter_table('statistical_test', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statistical_test_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statistical_test_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statistical_test', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statistical_test_id'))
        batch_op.drop_index(batch_op.f('ix_statistical_test_group_id'))

    op.drop_table('statistical_test')
    # ### end Alembic commands ###
