"""add converters column to model_session

Revision ID: 21b1178f2d9d
Revises: cf029e1c7ea6
Create Date: 2026-08-20 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b1178f2d9d'
down_revision: Union[str, None] = 'cf029e1c7ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('converters', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_session', schema=None) as batch_op:
        batch_op.drop_column('converters')

    # ### end Alembic commands ###
