"""se añade campo nested a runs

Revision ID: 517e2f3084cc
Revises: c735ce8850b5
Create Date: 2026-05-09 20:52:50.756198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517e2f3084cc'
down_revision: Union[str, None] = 'c735ce8850b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nested', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_column('nested')

    # ### end Alembic commands ###
