"""Remove pipelines

Revision ID: 977b3bcc300a
Revises: 98791b9df4f0
Create Date: 2026-03-31 16:47:09.453670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '977b3bcc300a'
down_revision: Union[str, None] = '98791b9df4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('steps', sqlite.JSON(), nullable=True),
    sa.Column('edges', sqlite.JSON(), nullable=True),
    sa.Column('exploration', sqlite.JSON(), nullable=True),
    sa.Column('train', sqlite.JSON(), nullable=True),
    sa.Column('prediction', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline'))
    )
    # ### end Alembic commands ###
