"""add rag tables

Revision ID: f06652057903
Revises: b4f9e70098e7
Create Date: 2026-04-17 02:11:23.522691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f06652057903'
down_revision: Union[str, None] = 'b4f9e70098e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('optional_metadata', sa.JSON(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document')),
    sa.UniqueConstraint('file_hash', name=op.f('uq_document_file_hash'))
    )
    op.create_table('rag_chunking_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_chunking_model'))
    )
    op.create_table('rag_embedding_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_embedding_model'))
    )
    op.create_table('rag_generation_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_generation_model'))
    )
    op.create_table('rag_prompt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_prompt'))
    )
    op.create_table('chunk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunking_model_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chunking_model_id'], ['rag_chunking_model.id'], name=op.f('fk_chunk_chunking_model_id_rag_chunking_model'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_chunk_document_id_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunk')),
    sa.UniqueConstraint('id', 'document_id', name='uix_chunk_document')
    )
    op.create_table('rag_dense_retriever',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('embedding_model_id', sa.Integer(), nullable=False),
    sa.Column('document_ids', sa.JSON(), nullable=False),
    sa.Column('chunking_model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chunking_model_id'], ['rag_chunking_model.id'], name=op.f('fk_rag_dense_retriever_chunking_model_id_rag_chunking_model'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['embedding_model_id'], ['rag_embedding_model.id'], name=op.f('fk_rag_dense_retriever_embedding_model_id_rag_embedding_model'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_dense_retriever'))
    )
    op.create_table('rag_embedding_matrix',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunking_model_id', sa.Integer(), nullable=False),
    sa.Column('embedding_model_id', sa.Integer(), nullable=False),
    sa.Column('storage_folder', sa.String(), nullable=False),
    sa.Column('matrix_shape', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunking_model_id'], ['rag_chunking_model.id'], name=op.f('fk_rag_embedding_matrix_chunking_model_id_rag_chunking_model'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_rag_embedding_matrix_document_id_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['embedding_model_id'], ['rag_embedding_model.id'], name=op.f('fk_rag_embedding_matrix_embedding_model_id_rag_embedding_model'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_embedding_matrix')),
    sa.UniqueConstraint('document_id', 'chunking_model_id', 'embedding_model_id', name='uix_document_chunking_embedding')
    )
    op.create_table('rag_sparse_retriever',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('storage_folder', sa.String(), nullable=False),
    sa.Column('documents_ids', sa.JSON(), nullable=False),
    sa.Column('chunking_model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chunking_model_id'], ['rag_chunking_model.id'], name=op.f('fk_rag_sparse_retriever_chunking_model_id_rag_chunking_model'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_sparse_retriever'))
    )
    op.create_table('rag_retriever',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('dense_retriever_id', sa.Integer(), nullable=True),
    sa.Column('sparse_retriever_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("(class_name = 'SparseRetriever' AND sparse_retriever_id IS NOT NULL AND dense_retriever_id IS NULL) OR (class_name = 'DenseRetriever' AND dense_retriever_id IS NOT NULL AND sparse_retriever_id IS NULL)", name=op.f('ck_chk_retriever_type')),
    sa.ForeignKeyConstraint(['dense_retriever_id'], ['rag_dense_retriever.id'], name=op.f('fk_rag_retriever_dense_retriever_id_rag_dense_retriever'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sparse_retriever_id'], ['rag_sparse_retriever.id'], name=op.f('fk_rag_retriever_sparse_retriever_id_rag_sparse_retriever'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_retriever'))
    )
    op.create_table('rag_pipeline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('chunking_model_id', sa.Integer(), nullable=False),
    sa.Column('retriever_model_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('generation_model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chunking_model_id'], ['rag_chunking_model.id'], name=op.f('fk_rag_pipeline_chunking_model_id_rag_chunking_model'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generation_model_id'], ['rag_generation_model.id'], name=op.f('fk_rag_pipeline_generation_model_id_rag_generation_model'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['rag_prompt.id'], name=op.f('fk_rag_pipeline_prompt_id_rag_prompt'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retriever_model_id'], ['rag_retriever.id'], name=op.f('fk_rag_pipeline_retriever_model_id_rag_retriever'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['generative_session.id'], name=op.f('fk_rag_pipeline_session_id_generative_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_pipeline'))
    )
    op.create_table('rag_document_pipeline_session_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_rag_document_pipeline_session_link_document_id_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['rag_pipeline.id'], name=op.f('fk_rag_document_pipeline_session_link_pipeline_id_rag_pipeline'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['generative_session.id'], name=op.f('fk_rag_document_pipeline_session_link_session_id_generative_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_document_pipeline_session_link')),
    sa.UniqueConstraint('document_id', 'pipeline_id', name='uix_document_pipeline'),
    sa.UniqueConstraint('document_id', 'session_id', name='uix_document_session'),
    sa.UniqueConstraint('session_id', 'pipeline_id', name='uix_session_pipeline')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rag_document_pipeline_session_link')
    op.drop_table('rag_pipeline')
    op.drop_table('rag_retriever')
    op.drop_table('rag_sparse_retriever')
    op.drop_table('rag_embedding_matrix')
    op.drop_table('rag_dense_retriever')
    op.drop_table('chunk')
    op.drop_table('rag_prompt')
    op.drop_table('rag_generation_model')
    op.drop_table('rag_embedding_model')
    op.drop_table('rag_chunking_model')
    op.drop_table('document')
    # ### end Alembic commands ###
