"""no-op (was: rename plugin.lastest_version)

Revision ID: f928e0b5203d
Revises: f06652057903
Create Date: 2026-04-24 18:55:45.236676

This revision was autogenerated while the RAG branch briefly renamed
``plugin.lastest_version`` to ``latest_version``. The rename is unrelated to
RAG and was reverted, so this revision is kept only to preserve the chain for
databases already stamped with it.

The original body added ``latest_version`` as NOT NULL with no server default
and dropped the old column, which fails under SQLite batch mode on any database
that already has plugin rows (``NOT NULL constraint failed:
_alembic_tmp_plugin.latest_version``) and blocks startup.
"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f928e0b5203d"
down_revision: Union[str, None] = "f06652057903"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
