"""RAG tables added

Revision ID: f928e0b5203d
Revises: f06652057903
Create Date: 2026-04-24 18:55:45.236676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f928e0b5203d'
down_revision: Union[str, None] = 'f06652057903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plugin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latest_version', sa.String(), nullable=False))
        batch_op.drop_column('lastest_version')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plugin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastest_version', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('latest_version')

    # ### end Alembic commands ###
