"""Shared execution of converter fit/transform chains over dataset partitions.

Used by both the notebook flow (`DashAI.back.job.converter_job`, which fits
converters once over a full dataset) and the session/training flow
(`DashAI.back.job.model_job`, which must fit converters only on the training
partition of a holdout split or of each cross-validation fold, then apply the
already-fitted transformation to the rest of the split/fold).
"""

import logging
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Tuple

from DashAI.back.job.base_job import JobError

if TYPE_CHECKING:
    from DashAI.back.dataloaders.classes.dashai_dataset import DashAIDataset
    from DashAI.back.dependencies.registry import ComponentRegistry

log = logging.getLogger(__name__)


def rebuild_dataset_with_transformed_columns(
    base: "DashAIDataset",
    transformed: "DashAIDataset",
    scope_column_names: List[str],
    scope_column_indexes: List[int],
) -> "DashAIDataset":
    """
    Replaces specific columns in the base dataset with columns from the transformed
    dataset, preserving their original positions. Also appends any additional columns
    that were generated by the transformer at the end. Keeps the features and metadata
    consistent.

    Parameters
    ----------
    base : DashAIDataset
        The original dataset before transformation.

    transformed : DashAIDataset
        The dataset resulting from applying a transformer, containing updated and/or
        new columns.

    scope_column_names : List[str]
        Names of the columns that were originally selected for transformation.

    scope_column_indexes : List[int]
        The indices of the columns in the base dataset that were replaced.
        Must match the order of scope_column_names.

    Returns
    -------
    DashAIDataset
        A new dataset with the specified columns replaced in place, new columns
        appended, and original metadata and split information preserved.
    """
    from DashAI.back.dataloaders.classes.dashai_dataset import modify_table

    original_columns = base.column_names
    transformed_cols = transformed.column_names

    transformed_cols_set = set(transformed_cols)
    scope_column_names_set = set(scope_column_names)

    removed_cols = [
        col for col in scope_column_names if col not in transformed_cols_set
    ]
    replacement_cols = [
        col for col in scope_column_names if col in transformed_cols_set
    ]
    new_cols = [col for col in transformed_cols if col not in scope_column_names_set]

    removed_cols_set = set(removed_cols)

    new_columns_order = []
    seen_cols = set()
    for col in original_columns:
        if col in removed_cols_set:
            continue
        if col not in seen_cols:
            new_columns_order.append(col)
            seen_cols.add(col)

    col_name_mapping = {}
    for col in new_cols:
        unique_col = col
        counter = 1
        while unique_col in seen_cols:
            unique_col = f"{col}_{counter}"
            counter += 1
        new_columns_order.append(unique_col)
        seen_cols.add(unique_col)
        col_name_mapping[col] = unique_col

    updated_arrays = {}
    for col in replacement_cols:
        if col in transformed_cols_set:
            updated_arrays[col] = transformed.arrow_table[col]
    for col, unique_col in col_name_mapping.items():
        if col in transformed_cols_set:
            updated_arrays[unique_col] = transformed.arrow_table[col]

    updated_types = base.types.copy()

    for col in removed_cols:
        if col in updated_types:
            del updated_types[col]

    for col in replacement_cols:
        if col in transformed.types:
            updated_types[col] = transformed.types[col]
    for col, unique_col in col_name_mapping.items():
        if col in transformed.types:
            updated_types[unique_col] = transformed.types[col]

    # Use existing modify_table (imported at module level)
    modified_dataset = modify_table(base, updated_arrays, types=updated_types)
    modified_dataset = modified_dataset.select_columns(new_columns_order)

    return modified_dataset


def instantiate_converter(
    component_registry: "ComponentRegistry",
    converter_name: str,
    params: Optional[Dict[str, Any]] = None,
):
    """Instantiate a registered converter by name with the given constructor params.

    Parameters
    ----------
    component_registry : ComponentRegistry
        The DashAI component registry, used to resolve `converter_name` to a class.
    converter_name : str
        Name of the converter class as registered in the component registry.
    params : dict, optional
        Constructor keyword arguments for the converter. Defaults to None (no args).

    Returns
    -------
    BaseConverter
        A new, unfitted instance of the requested converter.

    Raises
    ------
    JobError
        If `converter_name` is not found in the component registry.
    """
    try:
        converter_constructor = component_registry[converter_name]["class"]
    except KeyError as e:
        log.exception(e)
        raise JobError(f"Error importing converter {converter_name}: {e}") from e
    return converter_constructor(**(params or {}))


def fit_transform_on_partition(
    converters_config: List[Dict[str, Any]],
    component_registry: "ComponentRegistry",
    x_train: "DashAIDataset",
    y_train: "DashAIDataset",
    x_others: Optional[Dict[str, "DashAIDataset"]] = None,
    partition_label: str = "train",
) -> Tuple["DashAIDataset", "DashAIDataset", Dict[str, "DashAIDataset"]]:
    """Fit a chain of converters only on `x_train`/`y_train`, then apply each
    already-fitted converter (never re-fit) to `x_train` and to every dataset in
    `x_others` (e.g. `validation`/`test`).

    Converters that change the row count (samplers, e.g. SMOTE) are the one
    exception: they only transform `train` — every entry in `x_others` is
    returned unchanged for that converter, since resampling a validation/test
    partition would corrupt the distribution being evaluated. They also always
    fit/transform over the *entire* `x_train`/`y_train`, ignoring any partial
    `columns` scope: resampling only a subset of the input columns would leave
    the model with a mismatched feature set.

    Parameters
    ----------
    converters_config : list of dict
        Ordered list of `{"converter": str, "params": dict, "columns": list[str]}`.
        An empty/missing `columns` means "all of x_train's current columns".
    component_registry : ComponentRegistry
        Used to resolve each `converter` name to a class.
    x_train : DashAIDataset
        The training partition's input columns.
    y_train : DashAIDataset
        The training partition's output column(s).
    x_others : dict of str to DashAIDataset, optional
        Other partitions of the same split (e.g. `{"validation": ..., "test": ...}`
        for holdout, or `{"test": ...}` for a CV fold) to transform with the same
        fitted converters. Defaults to None (no other partitions).
    partition_label : str, optional
        Human-readable label for the partition being fit on, used only in error
        messages (e.g. `"train"`, `"fold_2"`). Defaults to `"train"`.

    Returns
    -------
    tuple
        `(x_train, y_train, x_others)`, all transformed in place by the fitted
        converter chain. `y_train` only changes when a sampler resamples it;
        the `y` counterparts of `x_others` are never touched, since no converter
        in DashAI transforms output columns.
    """
    from DashAI.back.dataloaders.classes.dashai_dataset import (
        select_columns as split_x_y,
    )

    x_others = dict(x_others or {})

    for entry in converters_config:
        converter_name = entry["converter"]
        params = entry.get("params") or {}
        columns = entry.get("columns") or list(x_train.column_names)

        converter_instance = instantiate_converter(
            component_registry, converter_name, params
        )
        changes_row_count = bool(
            getattr(type(converter_instance), "CHANGES_ROW_COUNT", False)
        )
        supervised = bool(getattr(type(converter_instance), "SUPERVISED", False))

        if changes_row_count:
            # Samplers resample the whole feature set based on y; a partial
            # column scope would desync the model's expected input columns.
            X_fit = x_train
            y_fit = y_train
        else:
            X_fit = x_train.select_columns(columns)
            y_fit = y_train if supervised else None

        try:
            converter_instance = converter_instance.fit(X_fit, y_fit)
        except Exception as e:
            log.exception(e)
            raise JobError(
                f"Error fitting converter '{converter_name}' on partition "
                f"'{partition_label}': {e}"
            ) from e

        try:
            transformed_train = converter_instance.transform(X_fit, y_fit)
        except Exception as e:
            log.exception(e)
            raise JobError(
                f"Error transforming '{partition_label}' with '{converter_name}': {e}"
            ) from e

        if changes_row_count:
            input_columns = list(x_train.column_names)
            output_columns = list(y_train.column_names)
            x_train, y_train = split_x_y(
                transformed_train, input_columns, output_columns
            )
            # Samplers only ever affect train; validation/test partitions of
            # this same split are intentionally left untouched below.
            continue

        x_train = rebuild_dataset_with_transformed_columns(
            x_train,
            transformed_train,
            columns,
            [x_train.column_names.index(c) for c in columns],
        )

        for split_name, x_other in list(x_others.items()):
            if x_other is None or len(x_other) == 0:
                continue
            try:
                transformed_other = converter_instance.transform(
                    x_other.select_columns(columns)
                )
            except Exception as e:
                log.exception(e)
                raise JobError(
                    f"Error transforming '{split_name}' with '{converter_name}': {e}"
                ) from e
            x_others[split_name] = rebuild_dataset_with_transformed_columns(
                x_other,
                transformed_other,
                columns,
                [x_other.column_names.index(c) for c in columns],
            )

    return x_train, y_train, x_others


def apply_session_converters(
    x: Any,
    y: Any,
    converters_config: Optional[List[Dict[str, Any]]],
    component_registry: "ComponentRegistry",
) -> Tuple[Any, Any]:
    """Apply session-level converters to the output of a `BaseSplitter.split()` call.

    `x`/`y` are either a single `DatasetDict` with keys `train`/`validation`/`test`
    (holdout), or a list of `DatasetDict` with keys `train`/`test` (cross-validation:
    one entry per fold, plus a final `"full_dataset"` entry whose `train` is the
    entire dataset, used to train the production model). Each partition/fold gets
    its own independent fit — no fold ever "sees" another fold's data through a
    converter, and the CV `full_dataset` entry is fit on the whole dataset exactly
    as intended, with no special-casing needed.

    Parameters
    ----------
    x : DatasetDict or list of DatasetDict
        Input-column partitions/folds, as returned by a splitter's `split()`.
    y : DatasetDict or list of DatasetDict
        Output-column partitions/folds, matching the shape of `x`.
    converters_config : list of dict or None
        The `ModelSession.converters` configuration. If empty/None, `x`/`y` are
        returned unchanged.
    component_registry : ComponentRegistry
        Used to resolve converter names to classes.

    Returns
    -------
    tuple
        `(x, y)` with the same shape as the input, with converters applied.
    """
    from datasets import DatasetDict

    if not converters_config:
        return x, y

    if isinstance(x, list):
        new_x, new_y = [], []
        last_index = len(x) - 1
        for i, (x_fold, y_fold) in enumerate(zip(x, y, strict=True)):
            x_others = {k: v for k, v in x_fold.items() if k != "train"}
            y_others = {k: v for k, v in y_fold.items() if k != "train"}
            label = "full_dataset" if i == last_index else f"fold_{i}"
            x_train, y_train, x_rest = fit_transform_on_partition(
                converters_config,
                component_registry,
                x_fold["train"],
                y_fold["train"],
                x_others=x_others,
                partition_label=label,
            )
            new_x.append(DatasetDict({"train": x_train, **x_rest}))
            new_y.append(DatasetDict({"train": y_train, **y_others}))
        return new_x, new_y

    x_others = {k: v for k, v in x.items() if k != "train"}
    y_others = {k: v for k, v in y.items() if k != "train"}
    x_train, y_train, x_rest = fit_transform_on_partition(
        converters_config,
        component_registry,
        x["train"],
        y["train"],
        x_others=x_others,
        partition_label="train",
    )
    return (
        DatasetDict({"train": x_train, **x_rest}),
        DatasetDict({"train": y_train, **y_others}),
    )
