"""Shared execution of converter fit/transform chains over dataset partitions.

Used by both the notebook flow (`DashAI.back.job.converter_job`, which fits
converters once over a full dataset) and the session/training flow
(`DashAI.back.job.model_job`, which must fit converters only on the training
partition of a holdout split or of each cross-validation fold, then apply the
already-fitted transformation to the rest of the split/fold).
"""

import logging
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Tuple

from DashAI.back.job.base_job import JobError

if TYPE_CHECKING:
    from DashAI.back.dataloaders.classes.dashai_dataset import DashAIDataset
    from DashAI.back.dependencies.registry import ComponentRegistry

log = logging.getLogger(__name__)


def rebuild_dataset_with_transformed_columns(
    base: "DashAIDataset",
    transformed: "DashAIDataset",
    scope_column_names: List[str],
    scope_column_indexes: List[int],
) -> "DashAIDataset":
    """
    Replaces specific columns in the base dataset with columns from the transformed
    dataset, preserving their original positions. Also appends any additional columns
    that were generated by the transformer at the end. Keeps the features and metadata
    consistent.

    Parameters
    ----------
    base : DashAIDataset
        The original dataset before transformation.

    transformed : DashAIDataset
        The dataset resulting from applying a transformer, containing updated and/or
        new columns.

    scope_column_names : List[str]
        Names of the columns that were originally selected for transformation.

    scope_column_indexes : List[int]
        The indices of the columns in the base dataset that were replaced.
        Must match the order of scope_column_names.

    Returns
    -------
    DashAIDataset
        A new dataset with the specified columns replaced in place, new columns
        appended, and original metadata and split information preserved.
    """
    from DashAI.back.dataloaders.classes.dashai_dataset import modify_table

    original_columns = base.column_names
    transformed_cols = transformed.column_names

    transformed_cols_set = set(transformed_cols)
    scope_column_names_set = set(scope_column_names)

    removed_cols = [
        col for col in scope_column_names if col not in transformed_cols_set
    ]
    replacement_cols = [
        col for col in scope_column_names if col in transformed_cols_set
    ]
    new_cols = [col for col in transformed_cols if col not in scope_column_names_set]

    removed_cols_set = set(removed_cols)

    new_columns_order = []
    seen_cols = set()
    for col in original_columns:
        if col in removed_cols_set:
            continue
        if col not in seen_cols:
            new_columns_order.append(col)
            seen_cols.add(col)

    col_name_mapping = {}
    for col in new_cols:
        unique_col = col
        counter = 1
        while unique_col in seen_cols:
            unique_col = f"{col}_{counter}"
            counter += 1
        new_columns_order.append(unique_col)
        seen_cols.add(unique_col)
        col_name_mapping[col] = unique_col

    updated_arrays = {}
    for col in replacement_cols:
        if col in transformed_cols_set:
            updated_arrays[col] = transformed.arrow_table[col]
    for col, unique_col in col_name_mapping.items():
        if col in transformed_cols_set:
            updated_arrays[unique_col] = transformed.arrow_table[col]

    updated_types = base.types.copy()

    for col in removed_cols:
        if col in updated_types:
            del updated_types[col]

    for col in replacement_cols:
        if col in transformed.types:
            updated_types[col] = transformed.types[col]
    for col, unique_col in col_name_mapping.items():
        if col in transformed.types:
            updated_types[unique_col] = transformed.types[col]

    # Use existing modify_table (imported at module level)
    modified_dataset = modify_table(base, updated_arrays, types=updated_types)
    modified_dataset = modified_dataset.select_columns(new_columns_order)

    return modified_dataset


def instantiate_converter(
    component_registry: "ComponentRegistry",
    converter_name: str,
    params: Optional[Dict[str, Any]] = None,
):
    """Instantiate a registered converter by name with the given constructor params.

    Parameters
    ----------
    component_registry : ComponentRegistry
        The DashAI component registry, used to resolve `converter_name` to a class.
    converter_name : str
        Name of the converter class as registered in the component registry.
    params : dict, optional
        Constructor keyword arguments for the converter. Defaults to None (no args).

    Returns
    -------
    BaseConverter
        A new, unfitted instance of the requested converter.

    Raises
    ------
    JobError
        If `converter_name` is not found in the component registry.
    """
    try:
        converter_constructor = component_registry[converter_name]["class"]
    except KeyError as e:
        log.exception(e)
        raise JobError(f"Error importing converter {converter_name}: {e}") from e
    return converter_constructor(**(params or {}))


def resolve_input_scope(
    entry: Dict[str, Any],
    x_train_columns: List[str],
    group_registry: Dict[Tuple[str, int], Dict[int, List[str]]],
    partition_index: int,
) -> List[str]:
    """Resolve one converter-config entry's column scope to real column names.

    Supports two shapes for backward compatibility: a literal `"columns"`
    list (used directly, as before), or the new `"input_scope"` list of
    atoms (`{"kind": "column", "name": ...}` or `{"kind": "group",
    "converter_id": ..., "slot": ...}`). An empty/missing scope of either
    kind means "all of x_train's current columns", same as today.

    Parameters
    ----------
    entry : dict
        One converter-config entry.
    x_train_columns : list of str
        The current partition's train columns, for the "no scope" fallback.
    group_registry : dict
        Maps `(converter_id, slot)` to `{partition_index: [real columns]}`,
        populated by earlier converters in the same `apply_session_converters`
        call (see that function).
    partition_index : int
        Which partition/fold this resolution is for (used to look up a
        per-fold group registry entry).

    Returns
    -------
    list of str
        Real column names.
    """
    if entry.get("columns"):
        return entry["columns"]

    input_scope = entry.get("input_scope")
    if not input_scope:
        return list(x_train_columns)

    resolved: List[str] = []
    for atom in input_scope:
        if atom["kind"] == "column":
            resolved.append(atom["name"])
        else:
            key = (atom["converter_id"], atom["slot"])
            per_partition = group_registry.get(key, {})
            atom_columns = per_partition.get(partition_index, [])
            if not atom_columns:
                raise JobError(
                    f"Input scope references converter_id={atom['converter_id']!r} "
                    f"slot={atom['slot']!r}, but that group produced no columns "
                    f"for partition index {partition_index}. This usually means "
                    f"the referenced converter never ran before this one, or "
                    f"never emitted that slot for this partition (e.g. an "
                    f"optional output like SimpleImputer's indicator columns, "
                    f"which only exist when add_indicator is enabled)."
                )
            resolved.extend(atom_columns)
    return resolved


def record_group_columns(
    entry: Dict[str, Any],
    converter_instance: Any,
    before_columns: List[str],
    after_columns: List[str],
    resolved_scope: List[str],
    group_registry: Dict[Tuple[str, int], Dict[int, List[str]]],
    partition_indexes: List[int],
) -> None:
    """Record which real columns this converter produced, per slot, for
    every given partition index.

    A column belongs to this converter if it's brand new (not in
    `before_columns`) or if it's one of the converter's own resolved scope
    columns that's still present after the transform (an in-place
    modification, e.g. `StandardScaler` keeping the same column names).
    Classification into slots is delegated to the converter instance
    itself (`classify_output_columns`). `converter_instance` must be the
    already-fitted instance (from `fit_transform_on_partition`'s returned
    `fitted_converters[i]["instance"]`), not a fresh throwaway one — some
    converters' classification depends on state only `fit()` sets (e.g.
    `ColumnArithmetic`'s `self._result_column_name`, known only after
    fitting), even though most just pattern-match column names and don't
    need any instance state at all.

    Parameters
    ----------
    partition_indexes : list of int
        The registry is written under every index in this list: a single
        index for a per-fold-independent fit, or every fold index at once
        for a fit-once-and-reuse converter (same resolved columns apply
        everywhere in that case).

    Notes
    -----
    A no-op when `entry` has no `"id"` — legacy configs built with a
    literal `"columns"` list (no session-level id assigned) can never be
    the target of a group reference in the first place, so there is
    nothing useful to record under.

    `real_columns` is ordered by each column's actual physical position in
    `after_columns` (the real, deterministic column order of the
    transformed/rebuilt dataset) — never by set-union iteration order.
    Python set order is a hash-dependent implementation detail, not a
    meaningful column ordering; a caller that pairs two different
    partitions' recorded lists positionally (e.g. to reuse a fit-once
    converter across a group whose real columns differ per partition)
    needs that order to reflect actual emission order, or the pairing
    would be a coin flip between correct and silently swapped.
    """
    converter_id = entry.get("id")
    if not converter_id:
        return

    before_set = set(before_columns)
    resolved_scope_set = set(resolved_scope)
    real_columns = [
        col
        for col in after_columns
        if col not in before_set or col in resolved_scope_set
    ]

    by_slot = converter_instance.classify_output_columns(real_columns)
    for slot, columns in by_slot.items():
        key = (converter_id, slot)
        group_registry.setdefault(key, {})
        for partition_index in partition_indexes:
            group_registry[key][partition_index] = columns


def fit_transform_on_partition(
    converters_config: List[Dict[str, Any]],
    component_registry: "ComponentRegistry",
    x_train: "DashAIDataset",
    y_train: "DashAIDataset",
    x_others: Optional[Dict[str, "DashAIDataset"]] = None,
    partition_label: str = "train",
) -> Tuple[
    "DashAIDataset", "DashAIDataset", Dict[str, "DashAIDataset"], List[Dict[str, Any]]
]:
    """Fit a chain of converters only on `x_train`/`y_train`, then apply each
    already-fitted converter (never re-fit) to `x_train` and to every dataset in
    `x_others` (e.g. `validation`/`test`).

    Converters that change the row count (samplers, e.g. SMOTE) are the one
    exception: they only transform `train` — every entry in `x_others` is
    returned unchanged for that converter, since resampling a validation/test
    partition would corrupt the distribution being evaluated. They also always
    fit/transform over the *entire* `x_train`/`y_train`, ignoring any partial
    `columns` scope: resampling only a subset of the input columns would leave
    the model with a mismatched feature set.

    Parameters
    ----------
    converters_config : list of dict
        Ordered list of `{"converter": str, "params": dict, "columns": list[str]}`.
        An empty/missing `columns` means "all of x_train's current columns".
    component_registry : ComponentRegistry
        Used to resolve each `converter` name to a class.
    x_train : DashAIDataset
        The training partition's input columns.
    y_train : DashAIDataset
        The training partition's output column(s).
    x_others : dict of str to DashAIDataset, optional
        Other partitions of the same split (e.g. `{"validation": ..., "test": ...}`
        for holdout, or `{"test": ...}` for a CV fold) to transform with the same
        fitted converters. Defaults to None (no other partitions).
    partition_label : str, optional
        Human-readable label for the partition being fit on, used only in error
        messages (e.g. `"train"`, `"fold_2"`). Defaults to `"train"`.

    Returns
    -------
    tuple
        `(x_train, y_train, x_others, fitted_converters)`. `x_train`/`y_train`/
        `x_others` are transformed in place by the fitted converter chain;
        `y_train` only changes when a sampler resamples it, and the `y`
        counterparts of `x_others` are never touched, since no converter in
        DashAI transforms output columns. `fitted_converters` is an ordered
        list of `{"instance": BaseConverter, "columns": list[str]}` for every
        *non-sampler* converter that was fit here — this is what must be
        replayed (via `transform_for_prediction`) on brand-new data at
        prediction time; samplers are excluded since resampling a single new
        prediction instance has no meaning.
    """
    from DashAI.back.dataloaders.classes.dashai_dataset import (
        select_columns as split_x_y,
    )

    x_others = dict(x_others or {})
    fitted_converters: List[Dict[str, Any]] = []

    for entry in converters_config:
        converter_name = entry["converter"]
        params = entry.get("params") or {}
        columns = entry.get("columns") or list(x_train.column_names)
        target_column = entry.get("target_column")

        converter_instance = instantiate_converter(
            component_registry, converter_name, params
        )
        changes_row_count = bool(
            getattr(type(converter_instance), "CHANGES_ROW_COUNT", False)
        )
        supervised = bool(getattr(type(converter_instance), "SUPERVISED", False))

        if changes_row_count:
            # Samplers resample the whole feature set based on y; a partial
            # column scope would desync the model's expected input columns.
            X_fit = x_train
            y_fit = (
                x_train.select_columns([target_column])
                if supervised and target_column
                else y_train
            )
        else:
            missing = [c for c in columns if c not in x_train.column_names]
            if missing:
                target_hits = [c for c in missing if c in y_train.column_names]
                if target_hits:
                    raise JobError(
                        f"Converter '{converter_name}' has {target_hits} in its "
                        f"scope, but that column is the session's own output "
                        f"column: it's separated into the target (y) before any "
                        f"converter runs, so a non-supervised converter never "
                        f"has access to it. Scope this converter to input "
                        f"feature columns only, not to the session's output "
                        f"column."
                    )
                raise JobError(
                    f"Converter '{converter_name}' has {missing} in its scope, "
                    f"but those columns aren't present in the training data "
                    f"for partition '{partition_label}'."
                )
            X_fit = x_train.select_columns(columns)
            if not supervised:
                y_fit = None
            elif target_column:
                # Local target for this converter only (e.g. a feature
                # selector applied before the session has a real output
                # column) — pulled from x_train, not y_train, since the
                # target hasn't been separated out yet at this point.
                y_fit = x_train.select_columns([target_column])
            else:
                y_fit = y_train

        try:
            converter_instance = converter_instance.fit(X_fit, y_fit)
        except Exception as e:
            log.exception(e)
            raise JobError(
                f"Error fitting converter '{converter_name}' on partition "
                f"'{partition_label}': {e}"
            ) from e

        try:
            transformed_train = converter_instance.transform(X_fit, y_fit)
        except Exception as e:
            log.exception(e)
            raise JobError(
                f"Error transforming '{partition_label}' with '{converter_name}': {e}"
            ) from e

        if changes_row_count:
            input_columns = list(x_train.column_names)
            output_columns = list(y_train.column_names)
            x_train, y_train = split_x_y(
                transformed_train, input_columns, output_columns
            )
            # Samplers only ever affect train; validation/test partitions of
            # this same split are intentionally left untouched below.
            continue

        x_train = rebuild_dataset_with_transformed_columns(
            x_train,
            transformed_train,
            columns,
            [x_train.column_names.index(c) for c in columns],
        )
        fitted_converters.append({"instance": converter_instance, "columns": columns})

        for split_name, x_other in list(x_others.items()):
            if x_other is None or len(x_other) == 0:
                continue
            try:
                transformed_other = converter_instance.transform(
                    x_other.select_columns(columns)
                )
            except Exception as e:
                log.exception(e)
                raise JobError(
                    f"Error transforming '{split_name}' with '{converter_name}': {e}"
                ) from e
            x_others[split_name] = rebuild_dataset_with_transformed_columns(
                x_other,
                transformed_other,
                columns,
                [x_other.column_names.index(c) for c in columns],
            )

    return x_train, y_train, x_others, fitted_converters


def apply_session_converters(
    x: Any,
    y: Any,
    converters_config: Optional[List[Dict[str, Any]]],
    component_registry: "ComponentRegistry",
) -> Tuple[Any, Any, List[Dict[str, Any]], Dict[Tuple[str, int], Dict[int, List[str]]]]:
    """Apply session-level converters to the output of a `BaseSplitter.split()` call.

    `x`/`y` are either a single `DatasetDict` with keys `train`/`validation`/`test`
    (holdout), or a list of `DatasetDict` with keys `train`/`test` (cross-validation:
    one entry per fold, plus a final `"full_dataset"` entry whose `train` is the
    entire dataset, used to train the production model). Each fold gets its own
    independent fit for SUPERVISED or CHANGES_ROW_COUNT converters (no fold ever
    "sees" another fold's target or resampling through those). A converter that is
    neither, one whose output structure can depend on which rows it saw, e.g. a
    text vectorizer's vocabulary, but that never reads the target, is instead fit
    once on `full_dataset` and reused (transform-only) everywhere else, so every
    fold ends up with the exact same columns. This is a deliberate, narrower
    exception to "no fold sees another fold's data": it only ever shares
    non-target-derived structure.

    Each converter's `input_scope` (or legacy literal `columns`) is resolved to
    real column names per partition just before that converter runs, using the
    real columns any earlier converter in the list actually produced on that
    same partition (see `resolve_input_scope`/`record_group_columns`). This
    resolution is additive: it does not change which converters fit once vs.
    per fold, only how each one's column scope is computed.

    Parameters
    ----------
    x : DatasetDict or list of DatasetDict
        Input-column partitions/folds, as returned by a splitter's `split()`.
    y : DatasetDict or list of DatasetDict
        Output-column partitions/folds, matching the shape of `x`.
    converters_config : list of dict or None
        The `ModelSession.converters` configuration. If empty/None, `x`/`y` are
        returned unchanged.
    component_registry : ComponentRegistry
        Used to resolve converter names to classes.

    Returns
    -------
    tuple
        `(x, y, fitted_converters, group_registry)`: `x`/`y` have the same shape
        as the input, with converters applied. `fitted_converters` is the list
        (see `fit_transform_on_partition`) belonging to the partition that trains
        the model actually persisted afterwards, the single `train` fit for
        holdout, or the final `full_dataset` fold's fit for cross-validation
        (the per-fold fits in between are only used to evaluate the model and
        are not kept). `group_registry` maps `(converter_id, slot)` to
        `{partition_index: [real column names]}` for every converter that ran,
        for every partition, used by the caller to resolve the session's own
        final input/output column selection (see the design spec, section E).
    """
    from datasets import DatasetDict

    group_registry: Dict[Tuple[str, int], Dict[int, List[str]]] = {}

    if not converters_config:
        return x, y, [], group_registry

    if isinstance(x, list):
        last_index = len(x) - 1
        x_state = [dict(fold) for fold in x]
        y_state = [dict(fold) for fold in y]
        fitted_converters: List[Dict[str, Any]] = []

        for entry in converters_config:
            converter_name = entry["converter"]
            params = entry.get("params") or {}
            converter_instance = instantiate_converter(
                component_registry, converter_name, params
            )
            supervised = bool(getattr(type(converter_instance), "SUPERVISED", False))
            changes_row_count = bool(
                getattr(type(converter_instance), "CHANGES_ROW_COUNT", False)
            )

            if supervised or changes_row_count:
                for i in range(len(x_state)):
                    label = "full_dataset" if i == last_index else f"fold_{i}"
                    before_columns = list(x_state[i]["train"].column_names)
                    resolved_columns = resolve_input_scope(
                        entry, before_columns, group_registry, i
                    )
                    resolved_entry = {**entry, "columns": resolved_columns}
                    single_entry_config = [resolved_entry]

                    x_others = {k: v for k, v in x_state[i].items() if k != "train"}
                    y_others = {k: v for k, v in y_state[i].items() if k != "train"}
                    x_train, y_train, x_rest, fold_fitted = fit_transform_on_partition(
                        single_entry_config,
                        component_registry,
                        x_state[i]["train"],
                        y_state[i]["train"],
                        x_others=x_others,
                        partition_label=label,
                    )
                    record_group_columns(
                        entry,
                        fold_fitted[0]["instance"]
                        if fold_fitted
                        else converter_instance,
                        before_columns,
                        list(x_train.column_names),
                        resolved_columns,
                        group_registry,
                        partition_indexes=[i],
                    )
                    x_state[i] = {"train": x_train, **x_rest}
                    y_state[i] = {"train": y_train, **y_others}
                    if i == last_index:
                        fitted_converters.extend(fold_fitted)
            else:
                # Key -> (dataset, owning partition index), so each entry's
                # OWN scope can be resolved independently below: a group
                # reference to an earlier per-fold-divergent SUPERVISED
                # converter can resolve to a different real column per
                # fold, even though this converter itself is fit once.
                other_partitions: Dict[str, "DashAIDataset"] = {}
                other_partition_index: Dict[str, int] = {}
                for i in range(len(x_state)):
                    if i == last_index:
                        continue
                    for split_name, x_part in x_state[i].items():
                        key = f"{i}:{split_name}"
                        other_partitions[key] = x_part
                        other_partition_index[key] = i
                for split_name, x_part in x_state[last_index].items():
                    if split_name != "train":
                        key = f"{last_index}:{split_name}"
                        other_partitions[key] = x_part
                        other_partition_index[key] = last_index

                before_columns = list(x_state[last_index]["train"].column_names)
                resolved_columns = resolve_input_scope(
                    entry, before_columns, group_registry, last_index
                )
                resolved_entry = {**entry, "columns": resolved_columns}
                single_entry_config = [resolved_entry]

                # Fit + transform only full_dataset's train here; every
                # other partition is transformed manually below (reusing
                # this same fitted instance, never re-fit) so each one can
                # use its OWN resolved scope instead of full_dataset's.
                x_train, y_train, _no_others, full_fitted = fit_transform_on_partition(
                    single_entry_config,
                    component_registry,
                    x_state[last_index]["train"],
                    y_state[last_index]["train"],
                    x_others={},
                    partition_label="full_dataset",
                )
                fitted_instance = full_fitted[0]["instance"] if full_fitted else None

                x_rest: Dict[str, "DashAIDataset"] = {}
                for key, x_part in other_partitions.items():
                    if x_part is None or len(x_part) == 0 or fitted_instance is None:
                        x_rest[key] = x_part
                        continue
                    part_index = other_partition_index[key]
                    part_before_columns = list(x_part.column_names)
                    part_columns = resolve_input_scope(
                        entry, part_before_columns, group_registry, part_index
                    )
                    try:
                        if set(part_columns) == set(resolved_columns):
                            # Exactly the same real columns the instance was
                            # fit on, at worst in a different order — select
                            # by the fit-time NAMES directly (an exact
                            # identity match, so the result already comes
                            # back under those same names) rather than
                            # guessing a positional correspondence.
                            selected = x_part.select_columns(resolved_columns)
                            transformed_part = fitted_instance.transform(selected)
                        else:
                            # Genuinely different real columns per partition
                            # (a group reference resolved to different
                            # column(s) in this fold) — no name to match by,
                            # so pairing falls back to each side's own
                            # physical/emission order (see
                            # `record_group_columns`, which now preserves
                            # that order deterministically instead of an
                            # arbitrary set union) as the best available
                            # provenance signal. Refuse outright — rather
                            # than guess — when the two sides don't even
                            # have the same number of columns, since no 1:1
                            # pairing can exist then.
                            if len(part_columns) != len(resolved_columns):
                                raise JobError(
                                    f"Converter '{converter_name}' "
                                    f"(id={entry.get('id')!r}) was fit once "
                                    f"on {len(resolved_columns)} column(s) "
                                    f"{resolved_columns!r}, but partition "
                                    f"'{key}' resolves its own scope to "
                                    f"{len(part_columns)} column(s) "
                                    f"{part_columns!r} — a fit-once "
                                    f"converter cannot be reused across a "
                                    f"differing number of columns per "
                                    f"partition."
                                )

                            # Some wrapped transformers (e.g. scikit-learn's,
                            # via pandas feature-name validation) reject a
                            # mismatched column name even when shape/dtype
                            # match, so rename to the fit-time names,
                            # transform, then rename the result back to this
                            # partition's own real names before rebuilding.
                            from DashAI.back.dataloaders.classes.dashai_dataset import (
                                to_dashai_dataset,
                            )

                            selected = x_part.select_columns(part_columns)
                            rename_to_fit_names = dict(
                                zip(part_columns, resolved_columns, strict=True)
                            )
                            selected = to_dashai_dataset(
                                selected.to_pandas().rename(columns=rename_to_fit_names)
                            )
                            transformed_part = fitted_instance.transform(selected)
                            rename_to_real_names = dict(
                                zip(resolved_columns, part_columns, strict=True)
                            )
                            transformed_part = to_dashai_dataset(
                                transformed_part.to_pandas().rename(
                                    columns=rename_to_real_names
                                )
                            )
                    except JobError:
                        raise
                    except Exception as e:
                        log.exception(e)
                        raise JobError(
                            f"Error transforming '{key}' with '{converter_name}': {e}"
                        ) from e
                    x_rest[key] = rebuild_dataset_with_transformed_columns(
                        x_part,
                        transformed_part,
                        part_columns,
                        [x_part.column_names.index(c) for c in part_columns],
                    )
                    # Recorded per-partition, using THIS partition's own
                    # before/after/scope — not full_dataset's — so a later
                    # group reference resolves each fold's real columns
                    # correctly instead of inheriting full_dataset's (see
                    # the record_group_columns call below for full_dataset
                    # itself, which is unaffected by this).
                    record_group_columns(
                        entry,
                        fitted_instance
                        if fitted_instance is not None
                        else converter_instance,
                        part_before_columns,
                        list(x_rest[key].column_names),
                        part_columns,
                        group_registry,
                        partition_indexes=[part_index],
                    )

                record_group_columns(
                    entry,
                    fitted_instance
                    if fitted_instance is not None
                    else converter_instance,
                    before_columns,
                    list(x_train.column_names),
                    resolved_columns,
                    group_registry,
                    partition_indexes=[last_index],
                )
                x_state[last_index]["train"] = x_train
                y_state[last_index]["train"] = y_train
                for key, transformed in x_rest.items():
                    fold_i_str, split_name = key.split(":", 1)
                    x_state[int(fold_i_str)][split_name] = transformed
                fitted_converters.extend(full_fitted)

        new_x = [DatasetDict(fold) for fold in x_state]
        new_y = [DatasetDict(fold) for fold in y_state]
        return new_x, new_y, fitted_converters, group_registry

    x_others = {k: v for k, v in x.items() if k != "train"}
    y_others = {k: v for k, v in y.items() if k != "train"}
    fitted_converters: List[Dict[str, Any]] = []
    x_train_current = x["train"]
    y_train_current = y["train"]

    for entry in converters_config:
        converter_name = entry["converter"]
        params = entry.get("params") or {}
        converter_instance = instantiate_converter(
            component_registry, converter_name, params
        )
        before_columns = list(x_train_current.column_names)
        resolved_columns = resolve_input_scope(entry, before_columns, group_registry, 0)
        resolved_entry = {**entry, "columns": resolved_columns}

        x_train_current, y_train_current, x_others, entry_fitted = (
            fit_transform_on_partition(
                [resolved_entry],
                component_registry,
                x_train_current,
                y_train_current,
                x_others=x_others,
                partition_label="train",
            )
        )
        record_group_columns(
            entry,
            entry_fitted[0]["instance"] if entry_fitted else converter_instance,
            before_columns,
            list(x_train_current.column_names),
            resolved_columns,
            group_registry,
            partition_indexes=[0],
        )
        fitted_converters.extend(entry_fitted)

    return (
        DatasetDict({"train": x_train_current, **x_others}),
        DatasetDict({"train": y_train_current, **y_others}),
        fitted_converters,
        group_registry,
    )


def fitted_converters_path(run_path: str) -> str:
    """Path where a run's fitted session converters are stored.

    A sibling path next to `run_path` rather than something inside it,
    since `run_path` is a plain file for scikit-learn-style models (saved
    via `joblib.dump`) but a directory for HuggingFace-style models (saved
    via `save_pretrained`) — a sibling path is safe either way.
    """
    return f"{run_path}_converters.pkl"


def save_fitted_converters(
    run_path: str, fitted_converters: List[Dict[str, Any]]
) -> Optional[str]:
    """Persist the converters fitted for a run's final model, so they can be
    replayed (via `transform_for_prediction`) on new data at prediction time.

    Does nothing (returns None) when there are no session converters, so runs
    without them don't grow an empty file.
    """
    if not fitted_converters:
        return None

    import joblib

    path = fitted_converters_path(run_path)
    try:
        joblib.dump(fitted_converters, path)
    except Exception as e:
        log.exception(e)
        raise JobError(
            f"Error saving fitted converters for run at {run_path}: {e}"
        ) from e
    return path


def load_fitted_converters(run_path: str) -> List[Dict[str, Any]]:
    """Load the converters saved by `save_fitted_converters`, or `[]` if this
    run has none (e.g. it predates this feature, or the session had no
    converters configured)."""
    import os

    path = fitted_converters_path(run_path)
    if not os.path.exists(path):
        return []

    import joblib

    try:
        return joblib.load(path)
    except Exception as e:
        log.exception(e)
        raise JobError(f"Error loading fitted converters from {path}: {e}") from e


def transform_for_prediction(
    dataset: "DashAIDataset", fitted_converters: List[Dict[str, Any]]
) -> "DashAIDataset":
    """Apply already-fitted session converters (transform only, never fit) to
    new prediction input, replaying the exact transformation used when
    training the model these converters were saved alongside — the same
    `FilteredClassifier` principle used during training: the fitted filter is
    applied as-is, never re-fit on the data it's applied to.

    Converters that change row counts (samplers) are never part of
    `fitted_converters` in the first place (see `fit_transform_on_partition`),
    since resampling a single new prediction instance has no meaning.
    """
    for entry in fitted_converters:
        converter_instance = entry["instance"]
        columns = entry["columns"]
        try:
            transformed = converter_instance.transform(dataset.select_columns(columns))
        except Exception as e:
            log.exception(e)
            raise JobError(
                f"Error applying converter '{type(converter_instance).__name__}' "
                f"to prediction input: {e}"
            ) from e
        dataset = rebuild_dataset_with_transformed_columns(
            dataset,
            transformed,
            columns,
            [dataset.column_names.index(c) for c in columns],
        )
    return dataset
