"""Shared execution of converter fit/transform chains over dataset partitions.

Used by both the notebook flow (`DashAI.back.job.converter_job`, which fits
converters once over a full dataset) and the session/training flow
(`DashAI.back.job.model_job`, which must fit converters only on the training
partition of a holdout split or of each cross-validation fold, then apply the
already-fitted transformation to the rest of the split/fold).
"""

import logging
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Tuple

from DashAI.back.job.base_job import JobError

if TYPE_CHECKING:
    from DashAI.back.dataloaders.classes.dashai_dataset import DashAIDataset
    from DashAI.back.dependencies.registry import ComponentRegistry

log = logging.getLogger(__name__)


def rebuild_dataset_with_transformed_columns(
    base: "DashAIDataset",
    transformed: "DashAIDataset",
    scope_column_names: List[str],
    scope_column_indexes: List[int],
) -> "DashAIDataset":
    """
    Replaces specific columns in the base dataset with columns from the transformed
    dataset, preserving their original positions. Also appends any additional columns
    that were generated by the transformer at the end. Keeps the features and metadata
    consistent.

    Parameters
    ----------
    base : DashAIDataset
        The original dataset before transformation.

    transformed : DashAIDataset
        The dataset resulting from applying a transformer, containing updated and/or
        new columns.

    scope_column_names : List[str]
        Names of the columns that were originally selected for transformation.

    scope_column_indexes : List[int]
        The indices of the columns in the base dataset that were replaced.
        Must match the order of scope_column_names.

    Returns
    -------
    DashAIDataset
        A new dataset with the specified columns replaced in place, new columns
        appended, and original metadata and split information preserved.
    """
    from DashAI.back.dataloaders.classes.dashai_dataset import modify_table

    original_columns = base.column_names
    transformed_cols = transformed.column_names

    transformed_cols_set = set(transformed_cols)
    scope_column_names_set = set(scope_column_names)

    removed_cols = [
        col for col in scope_column_names if col not in transformed_cols_set
    ]
    replacement_cols = [
        col for col in scope_column_names if col in transformed_cols_set
    ]
    new_cols = [col for col in transformed_cols if col not in scope_column_names_set]

    removed_cols_set = set(removed_cols)

    new_columns_order = []
    seen_cols = set()
    for col in original_columns:
        if col in removed_cols_set:
            continue
        if col not in seen_cols:
            new_columns_order.append(col)
            seen_cols.add(col)

    col_name_mapping = {}
    for col in new_cols:
        unique_col = col
        counter = 1
        while unique_col in seen_cols:
            unique_col = f"{col}_{counter}"
            counter += 1
        new_columns_order.append(unique_col)
        seen_cols.add(unique_col)
        col_name_mapping[col] = unique_col

    updated_arrays = {}
    for col in replacement_cols:
        if col in transformed_cols_set:
            updated_arrays[col] = transformed.arrow_table[col]
    for col, unique_col in col_name_mapping.items():
        if col in transformed_cols_set:
            updated_arrays[unique_col] = transformed.arrow_table[col]

    updated_types = base.types.copy()

    for col in removed_cols:
        if col in updated_types:
            del updated_types[col]

    for col in replacement_cols:
        if col in transformed.types:
            updated_types[col] = transformed.types[col]
    for col, unique_col in col_name_mapping.items():
        if col in transformed.types:
            updated_types[unique_col] = transformed.types[col]

    # Use existing modify_table (imported at module level)
    modified_dataset = modify_table(base, updated_arrays, types=updated_types)
    modified_dataset = modified_dataset.select_columns(new_columns_order)

    return modified_dataset


def instantiate_converter(
    component_registry: "ComponentRegistry",
    converter_name: str,
    params: Optional[Dict[str, Any]] = None,
):
    """Instantiate a registered converter by name with the given constructor params.

    Parameters
    ----------
    component_registry : ComponentRegistry
        The DashAI component registry, used to resolve `converter_name` to a class.
    converter_name : str
        Name of the converter class as registered in the component registry.
    params : dict, optional
        Constructor keyword arguments for the converter. Defaults to None (no args).

    Returns
    -------
    BaseConverter
        A new, unfitted instance of the requested converter.

    Raises
    ------
    JobError
        If `converter_name` is not found in the component registry.
    """
    try:
        converter_constructor = component_registry[converter_name]["class"]
    except KeyError as e:
        log.exception(e)
        raise JobError(f"Error importing converter {converter_name}: {e}") from e
    return converter_constructor(**(params or {}))


def fit_transform_on_partition(
    converters_config: List[Dict[str, Any]],
    component_registry: "ComponentRegistry",
    x_train: "DashAIDataset",
    y_train: "DashAIDataset",
    x_others: Optional[Dict[str, "DashAIDataset"]] = None,
    partition_label: str = "train",
) -> Tuple[
    "DashAIDataset", "DashAIDataset", Dict[str, "DashAIDataset"], List[Dict[str, Any]]
]:
    """Fit a chain of converters only on `x_train`/`y_train`, then apply each
    already-fitted converter (never re-fit) to `x_train` and to every dataset in
    `x_others` (e.g. `validation`/`test`).

    Converters that change the row count (samplers, e.g. SMOTE) are the one
    exception: they only transform `train` — every entry in `x_others` is
    returned unchanged for that converter, since resampling a validation/test
    partition would corrupt the distribution being evaluated. They also always
    fit/transform over the *entire* `x_train`/`y_train`, ignoring any partial
    `columns` scope: resampling only a subset of the input columns would leave
    the model with a mismatched feature set.

    Parameters
    ----------
    converters_config : list of dict
        Ordered list of `{"converter": str, "params": dict, "columns": list[str]}`.
        An empty/missing `columns` means "all of x_train's current columns".
    component_registry : ComponentRegistry
        Used to resolve each `converter` name to a class.
    x_train : DashAIDataset
        The training partition's input columns.
    y_train : DashAIDataset
        The training partition's output column(s).
    x_others : dict of str to DashAIDataset, optional
        Other partitions of the same split (e.g. `{"validation": ..., "test": ...}`
        for holdout, or `{"test": ...}` for a CV fold) to transform with the same
        fitted converters. Defaults to None (no other partitions).
    partition_label : str, optional
        Human-readable label for the partition being fit on, used only in error
        messages (e.g. `"train"`, `"fold_2"`). Defaults to `"train"`.

    Returns
    -------
    tuple
        `(x_train, y_train, x_others, fitted_converters)`. `x_train`/`y_train`/
        `x_others` are transformed in place by the fitted converter chain;
        `y_train` only changes when a sampler resamples it, and the `y`
        counterparts of `x_others` are never touched, since no converter in
        DashAI transforms output columns. `fitted_converters` is an ordered
        list of `{"instance": BaseConverter, "columns": list[str]}` for every
        *non-sampler* converter that was fit here — this is what must be
        replayed (via `transform_for_prediction`) on brand-new data at
        prediction time; samplers are excluded since resampling a single new
        prediction instance has no meaning.
    """
    from DashAI.back.dataloaders.classes.dashai_dataset import (
        select_columns as split_x_y,
    )

    x_others = dict(x_others or {})
    fitted_converters: List[Dict[str, Any]] = []

    for entry in converters_config:
        converter_name = entry["converter"]
        params = entry.get("params") or {}
        columns = entry.get("columns") or list(x_train.column_names)
        target_column = entry.get("target_column")

        converter_instance = instantiate_converter(
            component_registry, converter_name, params
        )
        changes_row_count = bool(
            getattr(type(converter_instance), "CHANGES_ROW_COUNT", False)
        )
        supervised = bool(getattr(type(converter_instance), "SUPERVISED", False))

        if changes_row_count:
            # Samplers resample the whole feature set based on y; a partial
            # column scope would desync the model's expected input columns.
            X_fit = x_train
            y_fit = (
                x_train.select_columns([target_column])
                if supervised and target_column
                else y_train
            )
        else:
            X_fit = x_train.select_columns(columns)
            if not supervised:
                y_fit = None
            elif target_column:
                # Local target for this converter only (e.g. a feature
                # selector applied before the session has a real output
                # column) — pulled from x_train, not y_train, since the
                # target hasn't been separated out yet at this point.
                y_fit = x_train.select_columns([target_column])
            else:
                y_fit = y_train

        try:
            converter_instance = converter_instance.fit(X_fit, y_fit)
        except Exception as e:
            log.exception(e)
            raise JobError(
                f"Error fitting converter '{converter_name}' on partition "
                f"'{partition_label}': {e}"
            ) from e

        try:
            transformed_train = converter_instance.transform(X_fit, y_fit)
        except Exception as e:
            log.exception(e)
            raise JobError(
                f"Error transforming '{partition_label}' with '{converter_name}': {e}"
            ) from e

        if changes_row_count:
            input_columns = list(x_train.column_names)
            output_columns = list(y_train.column_names)
            x_train, y_train = split_x_y(
                transformed_train, input_columns, output_columns
            )
            # Samplers only ever affect train; validation/test partitions of
            # this same split are intentionally left untouched below.
            continue

        x_train = rebuild_dataset_with_transformed_columns(
            x_train,
            transformed_train,
            columns,
            [x_train.column_names.index(c) for c in columns],
        )
        fitted_converters.append({"instance": converter_instance, "columns": columns})

        for split_name, x_other in list(x_others.items()):
            if x_other is None or len(x_other) == 0:
                continue
            try:
                transformed_other = converter_instance.transform(
                    x_other.select_columns(columns)
                )
            except Exception as e:
                log.exception(e)
                raise JobError(
                    f"Error transforming '{split_name}' with '{converter_name}': {e}"
                ) from e
            x_others[split_name] = rebuild_dataset_with_transformed_columns(
                x_other,
                transformed_other,
                columns,
                [x_other.column_names.index(c) for c in columns],
            )

    return x_train, y_train, x_others, fitted_converters


def apply_session_converters(
    x: Any,
    y: Any,
    converters_config: Optional[List[Dict[str, Any]]],
    component_registry: "ComponentRegistry",
) -> Tuple[Any, Any, List[Dict[str, Any]]]:
    """Apply session-level converters to the output of a `BaseSplitter.split()` call.

    `x`/`y` are either a single `DatasetDict` with keys `train`/`validation`/`test`
    (holdout), or a list of `DatasetDict` with keys `train`/`test` (cross-validation:
    one entry per fold, plus a final `"full_dataset"` entry whose `train` is the
    entire dataset, used to train the production model). Each fold gets its own
    independent fit for SUPERVISED or CHANGES_ROW_COUNT converters (no fold ever
    "sees" another fold's target or resampling through those). A converter that is
    neither — one whose output structure can depend on which rows it saw, e.g. a
    text vectorizer's vocabulary, but that never reads the target — is instead fit
    once on `full_dataset` and reused (transform-only) everywhere else, so every
    fold ends up with the exact same columns. This is a deliberate, narrower
    exception to "no fold sees another fold's data": it only ever shares
    non-target-derived structure.

    Parameters
    ----------
    x : DatasetDict or list of DatasetDict
        Input-column partitions/folds, as returned by a splitter's `split()`.
    y : DatasetDict or list of DatasetDict
        Output-column partitions/folds, matching the shape of `x`.
    converters_config : list of dict or None
        The `ModelSession.converters` configuration. If empty/None, `x`/`y` are
        returned unchanged.
    component_registry : ComponentRegistry
        Used to resolve converter names to classes.

    Returns
    -------
    tuple
        `(x, y, fitted_converters)`: `x`/`y` have the same shape as the input,
        with converters applied. `fitted_converters` is the list (see
        `fit_transform_on_partition`) belonging to the partition that trains
        the model actually persisted afterwards — the single `train` fit for
        holdout, or the final `full_dataset` fold's fit for cross-validation
        (the per-fold fits in between are only used to *evaluate* the model
        and are not kept).
    """
    from datasets import DatasetDict

    if not converters_config:
        return x, y, []

    if isinstance(x, list):
        last_index = len(x) - 1
        # Mutable per-fold state, advanced converter-by-converter (not
        # fold-by-fold) so a converter fit once on full_dataset can be
        # applied to every fold's *current* state, in the same chain order
        # a fold-by-fold loop would produce.
        x_state = [dict(fold) for fold in x]
        y_state = [dict(fold) for fold in y]
        fitted_converters: List[Dict[str, Any]] = []

        for entry in converters_config:
            converter_name = entry["converter"]
            params = entry.get("params") or {}
            converter_instance = instantiate_converter(
                component_registry, converter_name, params
            )
            supervised = bool(getattr(type(converter_instance), "SUPERVISED", False))
            changes_row_count = bool(
                getattr(type(converter_instance), "CHANGES_ROW_COUNT", False)
            )
            single_entry_config = [entry]

            if supervised or changes_row_count:
                # Unchanged semantics: every fold (including full_dataset)
                # fits this converter independently, on only its own train.
                for i in range(len(x_state)):
                    label = "full_dataset" if i == last_index else f"fold_{i}"
                    x_others = {k: v for k, v in x_state[i].items() if k != "train"}
                    y_others = {k: v for k, v in y_state[i].items() if k != "train"}
                    x_train, y_train, x_rest, fold_fitted = fit_transform_on_partition(
                        single_entry_config,
                        component_registry,
                        x_state[i]["train"],
                        y_state[i]["train"],
                        x_others=x_others,
                        partition_label=label,
                    )
                    x_state[i] = {"train": x_train, **x_rest}
                    y_state[i] = {"train": y_train, **y_others}
                    if i == last_index:
                        fitted_converters.extend(fold_fitted)
            else:
                # Fit once on full_dataset's train; reuse (transform only,
                # never re-fit) on every other fold's every partition —
                # including full_dataset's own non-train partitions, if any.
                other_partitions: Dict[str, "DashAIDataset"] = {}
                for i in range(len(x_state)):
                    if i == last_index:
                        continue
                    for split_name, x_part in x_state[i].items():
                        other_partitions[f"{i}:{split_name}"] = x_part
                for split_name, x_part in x_state[last_index].items():
                    if split_name != "train":
                        other_partitions[f"{last_index}:{split_name}"] = x_part

                x_train, y_train, x_rest, full_fitted = fit_transform_on_partition(
                    single_entry_config,
                    component_registry,
                    x_state[last_index]["train"],
                    y_state[last_index]["train"],
                    x_others=other_partitions,
                    partition_label="full_dataset",
                )
                x_state[last_index]["train"] = x_train
                y_state[last_index]["train"] = y_train
                for key, transformed in x_rest.items():
                    fold_i_str, split_name = key.split(":", 1)
                    x_state[int(fold_i_str)][split_name] = transformed
                fitted_converters.extend(full_fitted)

        new_x = [DatasetDict(fold) for fold in x_state]
        new_y = [DatasetDict(fold) for fold in y_state]
        return new_x, new_y, fitted_converters

    x_others = {k: v for k, v in x.items() if k != "train"}
    y_others = {k: v for k, v in y.items() if k != "train"}
    x_train, y_train, x_rest, fitted_converters = fit_transform_on_partition(
        converters_config,
        component_registry,
        x["train"],
        y["train"],
        x_others=x_others,
        partition_label="train",
    )
    return (
        DatasetDict({"train": x_train, **x_rest}),
        DatasetDict({"train": y_train, **y_others}),
        fitted_converters,
    )


def fitted_converters_path(run_path: str) -> str:
    """Path where a run's fitted session converters are stored.

    A sibling path next to `run_path` rather than something inside it,
    since `run_path` is a plain file for scikit-learn-style models (saved
    via `joblib.dump`) but a directory for HuggingFace-style models (saved
    via `save_pretrained`) — a sibling path is safe either way.
    """
    return f"{run_path}_converters.pkl"


def save_fitted_converters(
    run_path: str, fitted_converters: List[Dict[str, Any]]
) -> Optional[str]:
    """Persist the converters fitted for a run's final model, so they can be
    replayed (via `transform_for_prediction`) on new data at prediction time.

    Does nothing (returns None) when there are no session converters, so runs
    without them don't grow an empty file.
    """
    if not fitted_converters:
        return None

    import joblib

    path = fitted_converters_path(run_path)
    try:
        joblib.dump(fitted_converters, path)
    except Exception as e:
        log.exception(e)
        raise JobError(
            f"Error saving fitted converters for run at {run_path}: {e}"
        ) from e
    return path


def load_fitted_converters(run_path: str) -> List[Dict[str, Any]]:
    """Load the converters saved by `save_fitted_converters`, or `[]` if this
    run has none (e.g. it predates this feature, or the session had no
    converters configured)."""
    import os

    path = fitted_converters_path(run_path)
    if not os.path.exists(path):
        return []

    import joblib

    try:
        return joblib.load(path)
    except Exception as e:
        log.exception(e)
        raise JobError(f"Error loading fitted converters from {path}: {e}") from e


def transform_for_prediction(
    dataset: "DashAIDataset", fitted_converters: List[Dict[str, Any]]
) -> "DashAIDataset":
    """Apply already-fitted session converters (transform only, never fit) to
    new prediction input, replaying the exact transformation used when
    training the model these converters were saved alongside — the same
    `FilteredClassifier` principle used during training: the fitted filter is
    applied as-is, never re-fit on the data it's applied to.

    Converters that change row counts (samplers) are never part of
    `fitted_converters` in the first place (see `fit_transform_on_partition`),
    since resampling a single new prediction instance has no meaning.
    """
    for entry in fitted_converters:
        converter_instance = entry["instance"]
        columns = entry["columns"]
        try:
            transformed = converter_instance.transform(dataset.select_columns(columns))
        except Exception as e:
            log.exception(e)
            raise JobError(
                f"Error applying converter '{type(converter_instance).__name__}' "
                f"to prediction input: {e}"
            ) from e
        dataset = rebuild_dataset_with_transformed_columns(
            dataset,
            transformed,
            columns,
            [dataset.column_names.index(c) for c in columns],
        )
    return dataset
