from DashAI.back.core.utils import MultilingualString
from DashAI.back.statistical_tests.base_statistical_test import BaseStatisticalTest
from DashAI.back.statistical_tests.statistical_test_result import (
    PairwiseResult,
    StatisticalTestResult,
)
from DashAI.back.statistical_tests.utils import CorrectionMethod, correct_p_values


class CorrectedPairedTTest(BaseStatisticalTest):
    """Corrected Paired t-test for comparing two models evaluated with cross-validation.

    Based on Nadeau & Bengio (2003), this test corrects the standard paired t-test
    to account for the fact that CV folds are not independent, sharing training data.
    The standard paired t-test underestimates variance in this setting, leading to
    inflated Type I error rates. The correction factor is:

        var_corrected = (1/k + n_test/n_train) * var_differences

    where k is the number of folds, n_test is the test set size per fold, and
    n_train is the training set size per fold.

    References
    ----------
    Nadeau, C., & Bengio, Y. (2003). Inference for the Generalization Error.
    Machine Learning, 52(3), 239-281.
    """

    DISPLAY_NAME: str = MultilingualString(
        en="Corrected paired t-test",
        es="Prueba t pareada corregida",
        pt="Teste t pareado corrigido",
        de="Korrigierter gepaarter t-Test",
        zh="校正配对 t 检验",
    )
    DESCRIPTION: str = MultilingualString(
        en=(
            "Parametric test for comparing two related groups. Requires normality",
            "of pairwise differences and corrects for inter-observation dependence ",
            "generated by cross-validation.",
        ),
        es=(
            "Prueba paramétrica para comparar dos grupos relacionados. ",
            "Requiere normalidad de las diferencias entre pares y corrige la ",
            "dependencia entre observaciones generada por la validación cruzada.",
        ),
        pt=(
            "Teste t pareado com correção para dependências de validação cruzada. ",
            "Requer normalidade nas diferenças entre pares e corrige a dependência ",
            "entre observações gerada pela validação cruzada.",
        ),
        de=(
            "Parametrischer Test zum Vergleich zweier verbundener Gruppen. ",
            "Erfordert Normalverteilung der paarweisen Differenzen und korrigiert ",
            "die durch Kreuzvalidierung entstehende Abhängigkeit zwischen ",
            "Beobachtungen.",
        ),
        zh=(
            "用于比较两个相关组的参数检验。要求配对差值服从正态分布，",
            "并对交叉验证引入的观测间依赖进行校正。",
        ),
    )
    ICON: str = "Tune"
    COLOR: str = "#64B5F6"

    @classmethod
    def get_metadata(cls) -> dict:
        """Metadata for Corrected Paired T-Test."""
        return {
            "icon": cls.ICON,
            "is_parametric": True,
            "is_posthoc": False,
            "min_runs": 2,
            "max_runs": None,
            "supports_alternative": True,
            "supports_correction": True,
            "interpretation": MultilingualString(
                en={
                    "significant": (
                        "There is a significant difference between the two models. "
                        "The results are statistically significantly different."
                    ),
                    "not_significant": (
                        "No significant difference between the two models. "
                        "They perform similarly."
                    ),
                },
                es={
                    "significant": (
                        "Hay una diferencia significativa entre los dos modelos. "
                        "Los resultados son estadísticamente significativamente "
                        "diferentes."
                    ),
                    "not_significant": (
                        "No hay diferencia significativa entre los dos modelos. "
                        "Tienen un rendimiento similar."
                    ),
                },
                pt={
                    "significant": (
                        "Há uma diferença significativa entre os dois modelos. "
                        "Os resultados são estatisticamente significativamente "
                        "diferentes."
                    ),
                    "not_significant": (
                        "Não há diferença significativa entre os dois modelos. "
                        "Eles têm desempenho similar."
                    ),
                },
                de={
                    "significant": (
                        "Zwischen den beiden Modellen besteht ein signifikanter "
                        "Unterschied. Die Ergebnisse unterscheiden sich statistisch"
                        " signifikant."
                    ),
                    "not_significant": (
                        "Zwischen den beiden Modellen besteht kein signifikanter"
                        " Unterschied. Sie schneiden ähnlich ab."
                    ),
                },
                zh={
                    "significant": ("两个模型之间存在显著差异。结果在统计上显著不同。"),
                    "not_significant": ("两个模型之间没有显著差异。它们的表现相似。"),
                },
            ),
        }

    def run(
        self,
        scores: dict[str, list[float]],  # {run_name: [fold_scores]}
        alpha: float = 0.05,
        alternative: str = "two-sided",
        correction_method: str | None = None,
        **kwargs,
    ) -> StatisticalTestResult:
        """Run the corrected paired t-test for cross-validated score differences.

        Parameters
        ----------
        scores : dict[str, list[float]]
            Mapping from model/run names to paired score vectors collected over
            the same cross-validation folds.
        alpha : float, optional
            Significance level used to decide whether the null hypothesis is
            rejected, by default 0.05.
        alternative : str, optional
            Direction of the alternative hypothesis: ``two-sided``, ``greater``,
            or ``less``.
        correction_method : str or None, optional
            Method used to adjust p-values when more than two models are being
            compared.

        Returns
        -------
        StatisticalTestResult
            A result object containing the corrected test statistic, p-value,
            significance decision, and additional details about the variance
            correction applied to the fold-wise differences.

        Raises
        ------
        ValueError
            If fewer than two score sets are provided, if the score vectors are
            not aligned, or if the corrected standard deviation is zero.
        """
        import numpy as np
        from scipy import stats

        if len(scores) < 2:
            raise ValueError(
                "Corrected Paired t-test requires at least two sets of scores."
            )

        run_names = list(scores.keys())

        if len(scores) == 2 and correction_method is None:
            scores1 = np.array(scores[run_names[0]])
            scores2 = np.array(scores[run_names[1]])

            if len(scores1) != len(scores2):
                raise ValueError(
                    "Both sets of scores must have the same number of observations."
                )

            k = len(scores1)  # number of folds

            # Ratio used in the correction factor.
            # For standard k-fold CV: n_test/n_train = (1/k) / (1 - 1/k) = 1/(k-1)
            # This is the standard approximation when dataset size is not available.
            correction_factor = (1 / k) + (1 / (k - 1))

            differences = scores1 - scores2
            mean_diff = np.mean(differences)
            var_diff = np.var(differences, ddof=1)

            # Apply Nadeau & Bengio correction to the variance
            corrected_var = correction_factor * var_diff
            corrected_std = np.sqrt(corrected_var)

            if corrected_std == 0:
                raise ValueError(
                    "Corrected standard deviation is zero — "
                    "all fold differences are identical."
                )

            # t-statistic with corrected variance
            t_statistic = mean_diff / corrected_std
            # Two-tailed p-value with k-1 degrees of freedom
            if alternative == "two-sided":
                p_value = 2 * stats.t.sf(np.abs(t_statistic), df=k - 1)
            elif alternative == "greater":
                p_value = stats.t.sf(t_statistic, df=k - 1)
            else:  # less
                p_value = stats.t.cdf(t_statistic, df=k - 1)

            significant = p_value < alpha

            return StatisticalTestResult(
                statistic=float(t_statistic),
                p_value=float(p_value),
                significant=significant,
                alpha=alpha,
                details={
                    "differences": differences.tolist(),
                    "mean_difference": float(mean_diff),
                    "correction_factor": float(correction_factor),
                    "corrected_variance": float(corrected_var),
                    "degrees_of_freedom": k - 1,
                    "alternative": alternative,
                },
            )

        preliminary_results = []
        pre_correction_p_values = []

        for i in range(len(run_names)):
            for j in range(i + 1, len(run_names)):
                scores1 = np.array(scores[run_names[i]])
                scores2 = np.array(scores[run_names[j]])

                if len(scores1) != len(scores2):
                    raise ValueError(
                        f"Both sets of scores for {run_names[i]} and {run_names[j]} "
                        "must have the same number of observations."
                    )

                k = len(scores1)  # number of folds
                correction_factor = (1 / k) + (1 / (k - 1))

                differences = scores1 - scores2
                mean_diff = np.mean(differences)
                var_diff = np.var(differences, ddof=1)
                corrected_var = correction_factor * var_diff
                corrected_std = np.sqrt(corrected_var)

                if corrected_std == 0:
                    raise ValueError(
                        f"Corrected standard deviation is zero for {run_names[i]} "
                        f"and {run_names[j]} — all fold differences are identical."
                    )

                t_statistic = mean_diff / corrected_std
                if alternative == "two-sided":
                    p_value = 2 * stats.t.sf(np.abs(t_statistic), df=k - 1)
                elif alternative == "greater":
                    p_value = stats.t.sf(t_statistic, df=k - 1)
                else:  # less
                    p_value = stats.t.cdf(t_statistic, df=k - 1)

                preliminary_results.append((run_names[i], run_names[j], t_statistic))
                pre_correction_p_values.append(float(p_value))

        corrected_p_values = correct_p_values(
            p_values=pre_correction_p_values,
            method=CorrectionMethod[correction_method.upper()],
            alpha=alpha,
        )

        results = [
            (a, b, stat, p)
            for (a, b, stat), p in zip(
                preliminary_results, corrected_p_values, strict=False
            )
        ]

        overall_significant = any(p < alpha for _, _, _, p in results)
        pairwise = []

        for a, b, stat, p in results:
            pairwise.append(
                PairwiseResult(
                    run_1=a,
                    run_2=b,
                    statistic=stat,
                    p_value=p,
                    significant=p < alpha,
                )
            )

        return StatisticalTestResult(
            statistic=float("nan"),
            p_value=float("nan"),
            significant=overall_significant,
            alpha=alpha,
            details={},
            posthoc=pairwise,
        )
