import { Box, Typography } from "@mui/material";
import PropTypes from "prop-types";
import { useCallback, useMemo, useRef, useState } from "react";
import FormSchema from "../../shared/FormSchema";
import FormSchemaContainer from "../../shared/FormSchemaContainer";
import { generateSequentialName } from "../../../utils/nameGenerator";
import FormInputWrapper from "../../configurableObject/Inputs/FormInputWrapper";
import InputWithDebounce from "../../shared/InputWithDebounce";
import { useTranslation } from "react-i18next";

/**
 * Right sidebar component for configuring dataloader parameters
 * Similar to ParamsBar in Generative section
 *
 * @param {string} selectedDataloader - The dataloader type to configure
 * @param {object} formSubmitRef - The reference to the form submit function
 * @param {function} setError - The function to set the error state
 * @param {array} existingDatasets - Array of existing datasets to avoid name conflicts
 * @param {function} onValuesChange - Callback function called when form values change
 */
export default function DataloaderConfigBar({
  selectedDataloader,
  formSubmitRef,
  setError,
  existingDatasets = [],
  onValuesChange,
}) {
  const [inferenceRows, setInferenceRows] = useState(1000);
  // Track FormSchema values separately so we can merge with inference_rows
  const schemaValuesRef = useRef({});
  const { t } = useTranslation(["common", "datasets"]);

  const { defaultName } = useMemo(
    () =>
      generateSequentialName({
        base: "Dataset",
        items: existingDatasets,
      }),
    [existingDatasets],
  );

  // Handler for when FormSchema values change - merge with inference_rows
  const handleFormSchemaValuesChange = useCallback(() => {
    const values = formSubmitRef?.current?.values || {};
    schemaValuesRef.current = values;
    if (onValuesChange) {
      onValuesChange({ ...values, inference_rows: inferenceRows });
    }
  }, [formSubmitRef, inferenceRows, onValuesChange]);

  // Handler for when inference_rows changes - merge with schema values
  const handleInferenceRowsChange = useCallback(
    (val) => {
      const numeric = val ? Number(val) : undefined;
      setInferenceRows(numeric);
      if (onValuesChange) {
        onValuesChange({ ...schemaValuesRef.current, inference_rows: numeric });
      }
    },
    [onValuesChange],
  );

  if (!selectedDataloader) {
    return (
      <Box
        display="flex"
        height="100%"
        width="100%"
        flexDirection="column"
        justifyContent="center"
        alignItems="center"
        bgcolor="background.box"
        borderRadius={2}
        p={3}
      >
        <Typography
          variant="body2"
          sx={{ color: "text.secondary", textAlign: "center" }}
        >
          {t("datasets:label.selectDataloaderToConfigure")}
        </Typography>
      </Box>
    );
  }

  return (
    <Box
      display="flex"
      height="100%"
      width="100%"
      flexDirection="column"
      justifyContent="flex-start"
      overflow="auto"
      bgcolor="background.box"
      pt={2}
      pb={2}
      data-tour="dataloader-config"
    >
      {/* Inferred configuration - displayed above the autogenerated schema form
          This section is not part of the dataloader schema and can be used to
          expose inferred/auxiliary parameters (like inference_rows) to the UI.
      */}
      <Box overflow="auto">
        <Box sx={{ px: 2, pt: 2 }}>
          <Typography
            sx={{
              fontSize: "16px",
              whiteSpace: "normal",
              wordBreak: "break-word",
              fontWeight: 500,
              textAlign: "center",
              pb: 2,
            }}
          >
            {t("datasets:label.inferredConfiguration")}
          </Typography>
          <FormInputWrapper
            description={t("datasets:label.inferenceRowsDescription")}
          >
            <InputWithDebounce
              variant="outlined"
              label={t("datasets:label.inferenceRows")}
              name="inference_rows"
              value={inferenceRows}
              onChange={handleInferenceRowsChange}
              type="number"
              helperText=" "
              margin="dense"
              inputProps={{ min: 1 }}
            />
          </FormInputWrapper>
        </Box>

        {/* Header */}
        <Box
          display="flex"
          justifyContent="center"
          alignItems="center"
          px={2}
          pt={0}
          pb={1}
        >
          <Typography
            sx={{
              fontSize: "16px",
              whiteSpace: "normal",
              wordBreak: "break-word",
              fontWeight: 500,
              textAlign: "center",
            }}
          >
            {t("datasets:label.dataloaderConfiguration")}
          </Typography>
        </Box>

        {/* Configuration Form */}
        <Box sx={{ px: 2, pb: 2, flex: 1 }}>
          <Typography
            variant="body2"
            sx={{ color: "text.secondary", mb: 2, textAlign: "center" }}
          >
            {selectedDataloader}
          </Typography>

          <FormSchemaContainer>
            <FormSchema
              autoSave
              model={selectedDataloader}
              formSubmitRef={formSubmitRef}
              setError={setError}
              initialValues={{ name: defaultName }}
              onValuesChange={handleFormSchemaValuesChange}
              showBorder={false}
            />
          </FormSchemaContainer>
        </Box>
      </Box>
    </Box>
  );
}

DataloaderConfigBar.propTypes = {
  selectedDataloader: PropTypes.string,
  formSubmitRef: PropTypes.shape({ current: PropTypes.any }),
  setError: PropTypes.func,
  existingDatasets: PropTypes.array,
  onValuesChange: PropTypes.func,
};
